const testArray = []
var light_red = { contains: [{ q: 1, bag: "bright_white" }, { q: 2, bag: "muted_yellow" }] };
testArray.push(light_red);
var dark_orange = { contains: [{ q: 3, bag: "bright_white" }, { q: 4, bag: "muted_yellow" }] };
testArray.push(dark_orange);
var bright_white = { contains: [{ q: 1, bag: "shiny_gold" }] };
testArray.push(bright_white);
var muted_yellow = { contains: [{ q: 2, bag: "shiny_gold" }, { q: 9, bag: "faded_blue" }] };
testArray.push(muted_yellow);
var shiny_gold = { contains: [{ q: 1, bag: "dark_olive" }, { q: 2, bag: "vibrant_plum" }] };
testArray.push(shiny_gold);
var dark_olive = { contains: [{ q: 3, bag: "faded_blue" }, { q: 4, bag: "dotted_black" }] };
testArray.push(dark_olive);
var vibrant_plum = { contains: [{ q: 5, bag: "faded_blue" }, { q: 6, bag: "dotted_black" }] };
testArray.push(vibrant_plum);
var faded_blue = { contains: [] };
testArray.push(faded_blue);
var dotted_black = { contains: [] };
testArray.push(dotted_black);

const challengeArray = [];
var striped_orange = { contains: [{ q: 1, bag: "vibrant_green" }, { q: 5, bag: "plaid_yellow" }, { q: 1, bag: "drab_magenta" }] };
challengeArray.push(striped_orange);
var dark_fuchsia = { contains: [{ q: 3, bag: "wavy_indigo" }, { q: 4, bag: "striped_lime" }] };
challengeArray.push(dark_fuchsia);
var clear_maroon = { contains: [{ q: 2, bag: "clear_gold" }, { q: 5, bag: "bright_salmon" }, { q: 5, bag: "wavy_tomato" }] };
challengeArray.push(clear_maroon);
var faded_tan = { contains: [{ q: 4, bag: "dim_brown" }] };
challengeArray.push(faded_tan);
var wavy_olive = { contains: [{ q: 3, bag: "faded_gray" }, { q: 2, bag: "posh_brown" }, { q: 3, bag: "striped_cyan" }] };
challengeArray.push(wavy_olive);
var light_plum = { contains: [{ q: 4, bag: "vibrant_plum" }] };
challengeArray.push(light_plum);
var vibrant_cyan = { contains: [{ q: 4, bag: "dotted_gold" }, { q: 4, bag: "bright_indigo" }, { q: 4, bag: "wavy_lime" }, { q: 3, bag: "clear_plum" }] };
challengeArray.push(vibrant_cyan);
var vibrant_beige = { contains: [{ q: 1, bag: "wavy_silver" }, { q: 4, bag: "shiny_indigo" }, { q: 2, bag: "wavy_aqua" }, { q: 1, bag: "mirrored_cyan" }] };
challengeArray.push(vibrant_beige);
var light_tomato = { contains: [{ q: 5, bag: "muted_green" }, { q: 2, bag: "striped_tomato" }, { q: 4, bag: "faded_aqua" }, { q: 2, bag: "muted_salmon" }] };
challengeArray.push(light_tomato);
var drab_white = { contains: [{ q: 5, bag: "faded_beige" }, { q: 1, bag: "light_purple" }, { q: 1, bag: "striped_white" }, { q: 4, bag: "muted_cyan" }] };
challengeArray.push(drab_white);
var faded_purple = { contains: [{ q: 5, bag: "posh_lime" }] };
challengeArray.push(faded_purple);
var striped_violet = { contains: [{ q: 1, bag: "dim_bronze" }, { q: 2, bag: "faded_plum" }] };
challengeArray.push(striped_violet);
var pale_teal = { contains: [{ q: 2, bag: "shiny_salmon" }, { q: 2, bag: "light_tomato" }, { q: 5, bag: "dim_coral" }] };
challengeArray.push(pale_teal);
var dull_lime = { contains: [{ q: 3, bag: "bright_tomato" }, { q: 3, bag: "dim_magenta" }, { q: 3, bag: "bright_cyan" }, { q: 2, bag: "dark_teal" }] };
challengeArray.push(dull_lime);
var dim_salmon = { contains: [{ q: 3, bag: "dark_chartreuse" }] };
challengeArray.push(dim_salmon);
var faded_teal = { contains: [{ q: 2, bag: "shiny_coral" }, { q: 4, bag: "dark_turquoise" }, { q: 3, bag: "wavy_black" }] };
challengeArray.push(faded_teal);
var dark_green = { contains: [{ q: 5, bag: "vibrant_green" }, { q: 4, bag: "clear_blue" }] };
challengeArray.push(dark_green);
var dim_black = { contains: [{ q: 2, bag: "vibrant_bronze" }] };
challengeArray.push(dim_black);
var light_yellow = { contains: [{ q: 2, bag: "faded_salmon" }, { q: 4, bag: "muted_aqua" }] };
challengeArray.push(light_yellow);
var drab_brown = { contains: [{ q: 3, bag: "clear_green" }, { q: 2, bag: "pale_aqua" }] };
challengeArray.push(drab_brown);
var dotted_tomato = { contains: [{ q: 3, bag: "vibrant_purple" }, { q: 3, bag: "vibrant_tomato" }, { q: 3, bag: "clear_lime" }, { q: 5, bag: "dim_gold" }] };
challengeArray.push(dotted_tomato);
var faded_orange = { contains: [{ q: 1, bag: "pale_brown" }] };
challengeArray.push(faded_orange);
var light_black = { contains: [{ q: 1, bag: "striped_silver" }, { q: 3, bag: "dim_brown" }, { q: 2, bag: "bright_cyan" }, { q: 3, bag: "striped_lime" }] };
challengeArray.push(light_black);
var plaid_turquoise = { contains: [{ q: 5, bag: "muted_fuchsia" }, { q: 1, bag: "dull_violet" }] };
challengeArray.push(plaid_turquoise);
var light_lime = { contains: [{ q: 1, bag: "clear_lime" }, { q: 5, bag: "wavy_blue" }] };
challengeArray.push(light_lime);
var plaid_blue = { contains: [{ q: 2, bag: "dotted_blue" }, { q: 5, bag: "light_brown" }, { q: 5, bag: "posh_teal" }] };
challengeArray.push(plaid_blue);
var vibrant_maroon = { contains: [{ q: 2, bag: "bright_lavender" }] };
challengeArray.push(vibrant_maroon);
var light_orange = { contains: [{ q: 1, bag: "wavy_magenta" }, { q: 3, bag: "clear_orange" }, { q: 4, bag: "striped_silver" }] };
challengeArray.push(light_orange);
var bright_beige = { contains: [{ q: 2, bag: "plaid_red" }, { q: 1, bag: "dull_aqua" }, { q: 3, bag: "bright_fuchsia" }] };
challengeArray.push(bright_beige);
var striped_crimson = { contains: [{ q: 3, bag: "faded_maroon" }, { q: 3, bag: "dull_chartreuse" }, { q: 4, bag: "mirrored_red" }, { q: 4, bag: "clear_orange" }] };
challengeArray.push(striped_crimson);
var posh_silver = { contains: [{ q: 3, bag: "pale_plum" }, { q: 4, bag: "light_salmon" }, { q: 5, bag: "light_purple" }] };
challengeArray.push(posh_silver);
var dull_white = { contains: [{ q: 2, bag: "dark_white" }] };
challengeArray.push(dull_white);
var bright_lime = { contains: [{ q: 4, bag: "clear_indigo" }, { q: 2, bag: "vibrant_green" }] };
challengeArray.push(bright_lime);
var bright_crimson = { contains: [{ q: 3, bag: "light_lime" }] };
challengeArray.push(bright_crimson);
var dull_lavender = { contains: [{ q: 3, bag: "vibrant_magenta" }] };
challengeArray.push(dull_lavender);
var pale_purple = { contains: [] };
challengeArray.push(pale_purple);
var vibrant_coral = { contains: [{ q: 3, bag: "bright_cyan" }, { q: 2, bag: "bright_tomato" }] };
challengeArray.push(vibrant_coral);
var posh_salmon = { contains: [{ q: 4, bag: "vibrant_magenta" }, { q: 3, bag: "dull_aqua" }] };
challengeArray.push(posh_salmon);
var dull_black = { contains: [{ q: 4, bag: "dotted_black" }] };
challengeArray.push(dull_black);
var shiny_salmon = { contains: [{ q: 2, bag: "faded_plum" }, { q: 5, bag: "clear_lavender" }, { q: 1, bag: "light_crimson" }, { q: 2, bag: "light_gray" }] };
challengeArray.push(shiny_salmon);
var vibrant_red = { contains: [{ q: 3, bag: "dim_bronze" }, { q: 1, bag: "striped_indigo" }, { q: 1, bag: "vibrant_silver" }] };
challengeArray.push(vibrant_red);
var plaid_beige = { contains: [{ q: 1, bag: "posh_purple" }, { q: 5, bag: "pale_bronze" }, { q: 1, bag: "dotted_white" }] };
challengeArray.push(plaid_beige);
var striped_bronze = { contains: [{ q: 1, bag: "wavy_salmon" }] };
challengeArray.push(striped_bronze);
var shiny_lavender = { contains: [{ q: 2, bag: "shiny_salmon" }, { q: 2, bag: "bright_salmon" }, { q: 4, bag: "posh_fuchsia" }] };
challengeArray.push(shiny_lavender);
var plaid_chartreuse = { contains: [{ q: 2, bag: "vibrant_bronze" }, { q: 1, bag: "dull_chartreuse" }, { q: 3, bag: "wavy_tomato" }] };
challengeArray.push(plaid_chartreuse);
var bright_chartreuse = { contains: [] };
challengeArray.push(bright_chartreuse);
var wavy_white = { contains: [{ q: 2, bag: "dim_blue" }, { q: 5, bag: "faded_silver" }, { q: 5, bag: "shiny_silver" }, { q: 2, bag: "shiny_beige" }] };
challengeArray.push(wavy_white);
var drab_beige = { contains: [{ q: 5, bag: "wavy_tomato" }] };
challengeArray.push(drab_beige);
var mirrored_teal = { contains: [{ q: 5, bag: "muted_lavender" }, { q: 4, bag: "dull_chartreuse" }] };
challengeArray.push(mirrored_teal);
var dotted_bronze = { contains: [{ q: 1, bag: "clear_magenta" }, { q: 2, bag: "muted_silver" }, { q: 5, bag: "muted_cyan" }] };
challengeArray.push(dotted_bronze);
var dim_red = { contains: [{ q: 5, bag: "shiny_fuchsia" }, { q: 3, bag: "dotted_white" }] };
challengeArray.push(dim_red);
var shiny_crimson = { contains: [{ q: 2, bag: "dull_white" }, { q: 2, bag: "vibrant_maroon" }] };
challengeArray.push(shiny_crimson);
var wavy_plum = { contains: [{ q: 5, bag: "light_crimson" }, { q: 4, bag: "clear_green" }] };
challengeArray.push(wavy_plum);
var faded_olive = { contains: [{ q: 5, bag: "posh_cyan" }] };
challengeArray.push(faded_olive);
var mirrored_gold = { contains: [{ q: 5, bag: "striped_gold" }] };
challengeArray.push(mirrored_gold);
var dim_cyan = { contains: [{ q: 5, bag: "shiny_green" }, { q: 5, bag: "wavy_blue" }, { q: 3, bag: "mirrored_lime" }, { q: 4, bag: "dark_plum" }] };
challengeArray.push(dim_cyan);
var vibrant_orange = { contains: [{ q: 2, bag: "mirrored_lime" }, { q: 1, bag: "bright_chartreuse" }, { q: 3, bag: "pale_crimson" }, { q: 4, bag: "muted_beige" }] };
challengeArray.push(vibrant_orange);
var pale_beige = { contains: [{ q: 5, bag: "dull_olive" }] };
challengeArray.push(pale_beige);
var posh_lavender = { contains: [{ q: 1, bag: "faded_red" }, { q: 2, bag: "wavy_maroon" }] };
challengeArray.push(posh_lavender);
var plaid_teal = { contains: [{ q: 3, bag: "dull_black" }, { q: 5, bag: "muted_tan" }] };
challengeArray.push(plaid_teal);
var wavy_red = { contains: [{ q: 1, bag: "posh_salmon" }, { q: 1, bag: "light_black" }, { q: 2, bag: "drab_olive" }, { q: 4, bag: "drab_beige" }] };
challengeArray.push(wavy_red);
var drab_maroon = { contains: [{ q: 5, bag: "bright_yellow" }] };
challengeArray.push(drab_maroon);
var clear_tan = { contains: [{ q: 1, bag: "light_yellow" }, { q: 2, bag: "mirrored_indigo" }, { q: 2, bag: "dotted_olive" }, { q: 3, bag: "dim_magenta" }] };
challengeArray.push(clear_tan);
var striped_turquoise = { contains: [{ q: 1, bag: "posh_cyan" }, { q: 1, bag: "clear_crimson" }] };
challengeArray.push(striped_turquoise);
var posh_turquoise = { contains: [{ q: 3, bag: "bright_bronze" }, { q: 5, bag: "bright_orange" }] };
challengeArray.push(posh_turquoise);
var dark_turquoise = { contains: [{ q: 3, bag: "posh_yellow" }, { q: 4, bag: "dull_red" }, { q: 5, bag: "plaid_silver" }, { q: 3, bag: "bright_tomato" }] };
challengeArray.push(dark_turquoise);
var posh_green = { contains: [{ q: 2, bag: "wavy_bronze" }] };
challengeArray.push(posh_green);
var muted_green = { contains: [{ q: 2, bag: "bright_fuchsia" }, { q: 2, bag: "muted_gold" }, { q: 3, bag: "light_orange" }] };
challengeArray.push(muted_green);
var drab_salmon = { contains: [{ q: 3, bag: "light_black" }] };
challengeArray.push(drab_salmon);
var dotted_coral = { contains: [{ q: 4, bag: "pale_chartreuse" }] };
challengeArray.push(dotted_coral);
var dark_yellow = { contains: [{ q: 5, bag: "faded_red" }, { q: 5, bag: "pale_brown" }] };
challengeArray.push(dark_yellow);
var muted_teal = { contains: [{ q: 1, bag: "clear_gold" }, { q: 5, bag: "striped_tomato" }, { q: 2, bag: "dark_teal" }] };
challengeArray.push(muted_teal);
var bright_silver = { contains: [{ q: 2, bag: "bright_gray" }] };
challengeArray.push(bright_silver);
var drab_chartreuse = { contains: [{ q: 5, bag: "pale_teal" }] };
challengeArray.push(drab_chartreuse);
var muted_plum = { contains: [{ q: 3, bag: "posh_white" }, { q: 1, bag: "bright_red" }, { q: 5, bag: "striped_gold" }] };
challengeArray.push(muted_plum);
var dark_bronze = { contains: [{ q: 2, bag: "bright_cyan" }, { q: 1, bag: "dim_beige" }, { q: 1, bag: "pale_bronze" }, { q: 3, bag: "light_gray" }] };
challengeArray.push(dark_bronze);
var dim_fuchsia = { contains: [{ q: 3, bag: "dark_black" }, { q: 3, bag: "mirrored_chartreuse" }, { q: 3, bag: "faded_gray" }] };
challengeArray.push(dim_fuchsia);
var faded_brown = { contains: [{ q: 3, bag: "wavy_white" }, { q: 1, bag: "dull_violet" }] };
challengeArray.push(faded_brown);
var bright_green = { contains: [{ q: 4, bag: "vibrant_fuchsia" }, { q: 2, bag: "shiny_white" }, { q: 3, bag: "mirrored_blue" }, { q: 4, bag: "posh_aqua" }] };
challengeArray.push(bright_green);
var dotted_turquoise = { contains: [{ q: 1, bag: "shiny_beige" }, { q: 3, bag: "wavy_blue" }] };
challengeArray.push(dotted_turquoise);
var wavy_chartreuse = { contains: [{ q: 5, bag: "dark_plum" }] };
challengeArray.push(wavy_chartreuse);
var shiny_orange = { contains: [{ q: 4, bag: "clear_orange" }, { q: 4, bag: "dark_coral" }, { q: 2, bag: "bright_teal" }, { q: 5, bag: "dotted_brown" }] };
challengeArray.push(shiny_orange);
var shiny_gray = { contains: [{ q: 3, bag: "dull_olive" }, { q: 3, bag: "muted_aqua" }] };
challengeArray.push(shiny_gray);
var clear_blue = { contains: [{ q: 5, bag: "bright_salmon" }, { q: 2, bag: "shiny_gold" }] };
challengeArray.push(clear_blue);
var vibrant_olive = { contains: [{ q: 5, bag: "bright_salmon" }, { q: 1, bag: "muted_green" }, { q: 4, bag: "wavy_olive" }] };
challengeArray.push(vibrant_olive);
var muted_gold = { contains: [{ q: 3, bag: "striped_plum" }, { q: 4, bag: "dull_violet" }, { q: 1, bag: "shiny_green" }] };
challengeArray.push(muted_gold);
var plaid_aqua = { contains: [{ q: 4, bag: "shiny_purple" }, { q: 1, bag: "wavy_lime" }, { q: 3, bag: "striped_violet" }, { q: 4, bag: "clear_magenta" }] };
challengeArray.push(plaid_aqua);
var dim_bronze = { contains: [] };
challengeArray.push(dim_bronze);
var vibrant_turquoise = { contains: [{ q: 5, bag: "wavy_plum" }] };
challengeArray.push(vibrant_turquoise);
var light_teal = { contains: [{ q: 4, bag: "clear_plum" }, { q: 2, bag: "drab_crimson" }] };
challengeArray.push(light_teal);
var light_coral = { contains: [{ q: 1, bag: "drab_violet" }, { q: 3, bag: "light_yellow" }, { q: 2, bag: "faded_maroon" }] };
challengeArray.push(light_coral);
var bright_cyan = { contains: [{ q: 5, bag: "dim_crimson" }, { q: 3, bag: "striped_plum" }, { q: 2, bag: "muted_gold" }] };
challengeArray.push(bright_cyan);
var wavy_purple = { contains: [{ q: 4, bag: "vibrant_tomato" }, { q: 4, bag: "dull_bronze" }, { q: 1, bag: "dim_coral" }] };
challengeArray.push(wavy_purple);
var dull_tan = { contains: [{ q: 5, bag: "muted_fuchsia" }] };
challengeArray.push(dull_tan);
var bright_white = { contains: [{ q: 5, bag: "pale_blue" }] };
challengeArray.push(bright_white);
var clear_plum = { contains: [{ q: 2, bag: "muted_lavender" }, { q: 1, bag: "faded_aqua" }, { q: 1, bag: "faded_plum" }, { q: 3, bag: "dull_indigo" }] };
challengeArray.push(clear_plum);
var vibrant_tomato = { contains: [{ q: 1, bag: "posh_purple" }, { q: 5, bag: "mirrored_lime" }, { q: 3, bag: "vibrant_turquoise" }, { q: 4, bag: "clear_maroon" }] };
challengeArray.push(vibrant_tomato);
var muted_tan = { contains: [{ q: 2, bag: "dim_magenta" }, { q: 4, bag: "dotted_gray" }, { q: 4, bag: "plaid_orange" }, { q: 2, bag: "pale_green" }] };
challengeArray.push(muted_tan);
var dark_brown = { contains: [{ q: 5, bag: "striped_plum" }, { q: 2, bag: "mirrored_tomato" }, { q: 4, bag: "faded_plum" }, { q: 3, bag: "light_yellow" }] };
challengeArray.push(dark_brown);
var striped_yellow = { contains: [{ q: 5, bag: "muted_indigo" }, { q: 4, bag: "bright_black" }, { q: 3, bag: "clear_lime" }, { q: 1, bag: "striped_white" }] };
challengeArray.push(striped_yellow);
var posh_black = { contains: [{ q: 2, bag: "mirrored_tomato" }, { q: 4, bag: "posh_gray" }] };
challengeArray.push(posh_black);
var wavy_black = { contains: [{ q: 5, bag: "pale_orange" }, { q: 3, bag: "posh_violet" }, { q: 2, bag: "dotted_white" }, { q: 2, bag: "faded_red" }] };
challengeArray.push(wavy_black);
var muted_indigo = { contains: [{ q: 2, bag: "bright_fuchsia" }, { q: 4, bag: "muted_lavender" }] };
challengeArray.push(muted_indigo);
var bright_coral = { contains: [{ q: 1, bag: "posh_chartreuse" }, { q: 2, bag: "shiny_gold" }] };
challengeArray.push(bright_coral);
var posh_tomato = { contains: [{ q: 4, bag: "light_violet" }, { q: 1, bag: "mirrored_olive" }] };
challengeArray.push(posh_tomato);
var posh_cyan = { contains: [{ q: 2, bag: "mirrored_chartreuse" }, { q: 4, bag: "dotted_black" }, { q: 5, bag: "vibrant_gray" }] };
challengeArray.push(posh_cyan);
var pale_silver = { contains: [{ q: 1, bag: "light_fuchsia" }, { q: 4, bag: "dark_red" }] };
challengeArray.push(pale_silver);
var plaid_indigo = { contains: [{ q: 4, bag: "plaid_red" }, { q: 3, bag: "striped_cyan" }, { q: 1, bag: "muted_silver" }, { q: 2, bag: "wavy_magenta" }] };
challengeArray.push(plaid_indigo);
var dotted_indigo = { contains: [{ q: 1, bag: "mirrored_magenta" }, { q: 4, bag: "plaid_gold" }, { q: 3, bag: "dark_coral" }, { q: 2, bag: "vibrant_silver" }] };
challengeArray.push(dotted_indigo);
var light_chartreuse = { contains: [{ q: 5, bag: "shiny_blue" }, { q: 5, bag: "drab_coral" }, { q: 4, bag: "drab_turquoise" }] };
challengeArray.push(light_chartreuse);
var pale_tomato = { contains: [{ q: 3, bag: "wavy_violet" }, { q: 3, bag: "dotted_tan" }, { q: 4, bag: "drab_brown" }] };
challengeArray.push(pale_tomato);
var muted_chartreuse = { contains: [{ q: 3, bag: "dim_silver" }, { q: 1, bag: "dim_chartreuse" }, { q: 3, bag: "striped_green" }, { q: 3, bag: "dim_magenta" }] };
challengeArray.push(muted_chartreuse);
var dull_aqua = { contains: [{ q: 3, bag: "pale_crimson" }, { q: 2, bag: "drab_aqua" }, { q: 5, bag: "drab_magenta" }, { q: 3, bag: "clear_gold" }] };
challengeArray.push(dull_aqua);
var dark_lime = { contains: [{ q: 3, bag: "light_tan" }] };
challengeArray.push(dark_lime);
var dark_orange = { contains: [{ q: 4, bag: "drab_orange" }] };
challengeArray.push(dark_orange);
var faded_black = { contains: [{ q: 4, bag: "dotted_chartreuse" }, { q: 4, bag: "wavy_silver" }, { q: 5, bag: "plaid_olive" }, { q: 2, bag: "pale_blue" }] };
challengeArray.push(faded_black);
var dull_purple = { contains: [{ q: 1, bag: "clear_gold" }, { q: 5, bag: "wavy_lavender" }] };
challengeArray.push(dull_purple);
var dotted_gold = { contains: [{ q: 3, bag: "pale_purple" }, { q: 1, bag: "dark_olive" }, { q: 5, bag: "wavy_beige" }, { q: 2, bag: "mirrored_aqua" }] };
challengeArray.push(dotted_gold);
var pale_bronze = { contains: [{ q: 2, bag: "shiny_tomato" }, { q: 5, bag: "vibrant_turquoise" }] };
challengeArray.push(pale_bronze);
var bright_aqua = { contains: [{ q: 1, bag: "pale_teal" }, { q: 4, bag: "faded_coral" }, { q: 2, bag: "clear_olive" }] };
challengeArray.push(bright_aqua);
var faded_beige = { contains: [{ q: 5, bag: "wavy_yellow" }, { q: 3, bag: "pale_lavender" }, { q: 1, bag: "vibrant_coral" }] };
challengeArray.push(faded_beige);
var drab_turquoise = { contains: [{ q: 1, bag: "shiny_tomato" }, { q: 3, bag: "clear_lavender" }, { q: 2, bag: "drab_orange" }] };
challengeArray.push(drab_turquoise);
var light_maroon = { contains: [{ q: 1, bag: "posh_bronze" }, { q: 3, bag: "dotted_silver" }, { q: 1, bag: "plaid_silver" }, { q: 1, bag: "muted_teal" }] };
challengeArray.push(light_maroon);
var posh_maroon = { contains: [{ q: 1, bag: "mirrored_maroon" }, { q: 1, bag: "posh_black" }, { q: 3, bag: "faded_salmon" }, { q: 4, bag: "posh_gray" }] };
challengeArray.push(posh_maroon);
var bright_red = { contains: [{ q: 2, bag: "vibrant_salmon" }] };
challengeArray.push(bright_red);
var vibrant_purple = { contains: [{ q: 2, bag: "faded_violet" }] };
challengeArray.push(vibrant_purple);
var vibrant_crimson = { contains: [{ q: 3, bag: "plaid_yellow" }, { q: 3, bag: "dotted_yellow" }, { q: 2, bag: "pale_tan" }] };
challengeArray.push(vibrant_crimson);
var dim_green = { contains: [{ q: 3, bag: "faded_plum" }, { q: 4, bag: "posh_turquoise" }, { q: 4, bag: "muted_aqua" }] };
challengeArray.push(dim_green);
var striped_gray = { contains: [{ q: 1, bag: "striped_fuchsia" }] };
challengeArray.push(striped_gray);
var light_salmon = { contains: [{ q: 5, bag: "dim_coral" }, { q: 5, bag: "posh_brown" }, { q: 3, bag: "shiny_green" }, { q: 4, bag: "striped_beige" }] };
challengeArray.push(light_salmon);
var bright_violet = { contains: [{ q: 5, bag: "dim_maroon" }, { q: 5, bag: "dark_tan" }, { q: 3, bag: "drab_purple" }, { q: 2, bag: "muted_cyan" }] };
challengeArray.push(bright_violet);
var dotted_chartreuse = { contains: [{ q: 2, bag: "posh_lime" }] };
challengeArray.push(dotted_chartreuse);
var drab_silver = { contains: [{ q: 1, bag: "dim_coral" }, { q: 3, bag: "pale_chartreuse" }, { q: 1, bag: "light_salmon" }] };
challengeArray.push(drab_silver);
var mirrored_lime = { contains: [{ q: 4, bag: "light_orange" }, { q: 1, bag: "clear_orange" }, { q: 3, bag: "wavy_plum" }] };
challengeArray.push(mirrored_lime);
var muted_violet = { contains: [{ q: 5, bag: "faded_silver" }, { q: 4, bag: "posh_red" }, { q: 2, bag: "drab_aqua" }] };
challengeArray.push(muted_violet);
var dull_salmon = { contains: [{ q: 2, bag: "dull_maroon" }, { q: 3, bag: "mirrored_red" }] };
challengeArray.push(dull_salmon);
var posh_aqua = { contains: [{ q: 5, bag: "dim_turquoise" }, { q: 5, bag: "drab_green" }, { q: 2, bag: "striped_red" }] };
challengeArray.push(posh_aqua);
var muted_white = { contains: [{ q: 3, bag: "light_yellow" }, { q: 3, bag: "pale_yellow" }, { q: 2, bag: "dull_olive" }] };
challengeArray.push(muted_white);
var wavy_coral = { contains: [{ q: 3, bag: "wavy_lime" }, { q: 5, bag: "faded_purple" }, { q: 5, bag: "posh_gray" }, { q: 4, bag: "dark_tomato" }] };
challengeArray.push(wavy_coral);
var dark_silver = { contains: [{ q: 1, bag: "dull_chartreuse" }, { q: 2, bag: "dull_violet" }] };
challengeArray.push(dark_silver);
var dotted_plum = { contains: [{ q: 1, bag: "mirrored_violet" }, { q: 3, bag: "dim_crimson" }, { q: 1, bag: "mirrored_fuchsia" }, { q: 1, bag: "light_tan" }] };
challengeArray.push(dotted_plum);
var mirrored_purple = { contains: [{ q: 2, bag: "muted_lime" }, { q: 4, bag: "mirrored_teal" }, { q: 2, bag: "light_tomato" }] };
challengeArray.push(mirrored_purple);
var drab_yellow = { contains: [{ q: 4, bag: "drab_violet" }, { q: 3, bag: "striped_orange" }] };
challengeArray.push(drab_yellow);
var striped_teal = { contains: [{ q: 3, bag: "muted_cyan" }, { q: 1, bag: "light_fuchsia" }] };
challengeArray.push(striped_teal);
var drab_red = { contains: [{ q: 2, bag: "faded_coral" }, { q: 1, bag: "bright_crimson" }] };
challengeArray.push(drab_red);
var pale_orange = { contains: [{ q: 4, bag: "dull_chartreuse" }, { q: 4, bag: "clear_orange" }] };
challengeArray.push(pale_orange);
var posh_gold = { contains: [{ q: 2, bag: "faded_gray" }, { q: 5, bag: "striped_indigo" }] };
challengeArray.push(posh_gold);
var light_crimson = { contains: [] };
challengeArray.push(light_crimson);
var muted_red = { contains: [{ q: 5, bag: "dim_gray" }] };
challengeArray.push(muted_red);
var clear_cyan = { contains: [{ q: 5, bag: "faded_salmon" }, { q: 4, bag: "light_brown" }, { q: 3, bag: "muted_purple" }, { q: 5, bag: "striped_beige" }] };
challengeArray.push(clear_cyan);
var plaid_cyan = { contains: [{ q: 2, bag: "clear_yellow" }, { q: 4, bag: "shiny_gray" }, { q: 5, bag: "pale_green" }, { q: 1, bag: "posh_aqua" }] };
challengeArray.push(plaid_cyan);
var clear_brown = { contains: [{ q: 4, bag: "faded_lime" }, { q: 2, bag: "dull_bronze" }, { q: 2, bag: "clear_bronze" }] };
challengeArray.push(clear_brown);
var light_tan = { contains: [{ q: 3, bag: "light_bronze" }, { q: 4, bag: "drab_orange" }] };
challengeArray.push(light_tan);
var dim_indigo = { contains: [{ q: 4, bag: "shiny_fuchsia" }] };
challengeArray.push(dim_indigo);
var muted_black = { contains: [{ q: 4, bag: "pale_fuchsia" }, { q: 3, bag: "bright_maroon" }, { q: 3, bag: "striped_lavender" }] };
challengeArray.push(muted_black);
var faded_gray = { contains: [{ q: 3, bag: "wavy_plum" }, { q: 1, bag: "wavy_magenta" }, { q: 1, bag: "clear_lavender" }] };
challengeArray.push(faded_gray);
var mirrored_magenta = { contains: [{ q: 4, bag: "clear_blue" }] };
challengeArray.push(mirrored_magenta);
var dark_aqua = { contains: [{ q: 1, bag: "vibrant_blue" }, { q: 3, bag: "pale_aqua" }] };
challengeArray.push(dark_aqua);
var dim_lavender = { contains: [{ q: 1, bag: "clear_magenta" }, { q: 3, bag: "drab_blue" }] };
challengeArray.push(dim_lavender);
var bright_gray = { contains: [{ q: 1, bag: "dull_olive" }, { q: 1, bag: "plaid_lime" }, { q: 5, bag: "clear_blue" }] };
challengeArray.push(bright_gray);
var posh_teal = { contains: [{ q: 4, bag: "pale_yellow" }] };
challengeArray.push(posh_teal);
var pale_plum = { contains: [{ q: 2, bag: "bright_fuchsia" }, { q: 3, bag: "dotted_white" }, { q: 5, bag: "pale_crimson" }] };
challengeArray.push(pale_plum);
var mirrored_bronze = { contains: [{ q: 1, bag: "faded_yellow" }] };
challengeArray.push(mirrored_bronze);
var dull_plum = { contains: [{ q: 4, bag: "shiny_coral" }, { q: 3, bag: "posh_turquoise" }, { q: 2, bag: "muted_teal" }] };
challengeArray.push(dull_plum);
var plaid_silver = { contains: [{ q: 4, bag: "vibrant_black" }, { q: 4, bag: "dull_olive" }] };
challengeArray.push(plaid_silver);
var dull_violet = { contains: [{ q: 1, bag: "vibrant_magenta" }, { q: 3, bag: "faded_salmon" }, { q: 1, bag: "mirrored_aqua" }, { q: 4, bag: "light_crimson" }] };
challengeArray.push(dull_violet);
var dim_yellow = { contains: [{ q: 5, bag: "clear_coral" }, { q: 2, bag: "striped_white" }, { q: 5, bag: "clear_maroon" }] };
challengeArray.push(dim_yellow);
var drab_orange = { contains: [{ q: 4, bag: "dull_white" }, { q: 1, bag: "plaid_magenta" }, { q: 2, bag: "dull_lavender" }, { q: 4, bag: "dim_cyan" }] };
challengeArray.push(drab_orange);
var wavy_maroon = { contains: [{ q: 3, bag: "dull_violet" }, { q: 1, bag: "pale_brown" }, { q: 5, bag: "vibrant_magenta" }, { q: 5, bag: "mirrored_aqua" }] };
challengeArray.push(wavy_maroon);
var wavy_turquoise = { contains: [{ q: 5, bag: "wavy_crimson" }, { q: 1, bag: "posh_plum" }, { q: 4, bag: "faded_turquoise" }, { q: 5, bag: "striped_cyan" }] };
challengeArray.push(wavy_turquoise);
var clear_yellow = { contains: [{ q: 2, bag: "faded_purple" }, { q: 2, bag: "plaid_lime" }, { q: 4, bag: "clear_violet" }, { q: 4, bag: "drab_magenta" }] };
challengeArray.push(clear_yellow);
var muted_crimson = { contains: [{ q: 1, bag: "vibrant_orange" }] };
challengeArray.push(muted_crimson);
var drab_violet = { contains: [{ q: 2, bag: "pale_lavender" }, { q: 2, bag: "light_yellow" }] };
challengeArray.push(drab_violet);
var dull_cyan = { contains: [{ q: 5, bag: "dim_coral" }, { q: 1, bag: "posh_orange" }, { q: 3, bag: "striped_beige" }] };
challengeArray.push(dull_cyan);
var shiny_fuchsia = { contains: [{ q: 5, bag: "bright_lime" }, { q: 5, bag: "muted_aqua" }, { q: 5, bag: "dark_teal" }, { q: 5, bag: "faded_indigo" }] };
challengeArray.push(shiny_fuchsia);
var pale_chartreuse = { contains: [{ q: 4, bag: "dark_plum" }, { q: 5, bag: "clear_gold" }, { q: 2, bag: "wavy_blue" }, { q: 3, bag: "dim_coral" }] };
challengeArray.push(pale_chartreuse);
var dim_orange = { contains: [{ q: 1, bag: "vibrant_coral" }, { q: 1, bag: "clear_gold" }] };
challengeArray.push(dim_orange);
var shiny_tan = { contains: [{ q: 4, bag: "plaid_tan" }] };
challengeArray.push(shiny_tan);
var dull_bronze = { contains: [{ q: 5, bag: "dotted_lavender" }, { q: 2, bag: "wavy_plum" }] };
challengeArray.push(dull_bronze);
var muted_bronze = { contains: [{ q: 3, bag: "striped_white" }] };
challengeArray.push(muted_bronze);
var wavy_magenta = { contains: [{ q: 3, bag: "posh_lime" }, { q: 3, bag: "wavy_plum" }, { q: 5, bag: "bright_chartreuse" }] };
challengeArray.push(wavy_magenta);
var muted_cyan = { contains: [{ q: 1, bag: "pale_yellow" }, { q: 5, bag: "wavy_maroon" }, { q: 5, bag: "shiny_gold" }] };
challengeArray.push(muted_cyan);
var shiny_beige = { contains: [{ q: 5, bag: "posh_chartreuse" }, { q: 3, bag: "muted_indigo" }, { q: 3, bag: "wavy_plum" }] };
challengeArray.push(shiny_beige);
var vibrant_brown = { contains: [{ q: 2, bag: "shiny_green" }, { q: 2, bag: "pale_purple" }, { q: 3, bag: "posh_gray" }] };
challengeArray.push(vibrant_brown);
var dim_blue = { contains: [{ q: 4, bag: "clear_silver" }, { q: 4, bag: "muted_blue" }, { q: 2, bag: "clear_lavender" }] };
challengeArray.push(dim_blue);
var posh_chartreuse = { contains: [{ q: 2, bag: "wavy_magenta" }] };
challengeArray.push(posh_chartreuse);
var dim_magenta = { contains: [{ q: 3, bag: "faded_coral" }] };
challengeArray.push(dim_magenta);
var plaid_coral = { contains: [{ q: 2, bag: "drab_gray" }, { q: 4, bag: "dark_orange" }, { q: 2, bag: "dim_cyan" }] };
challengeArray.push(plaid_coral);
var dim_coral = { contains: [{ q: 1, bag: "shiny_salmon" }, { q: 3, bag: "wavy_plum" }, { q: 1, bag: "light_yellow" }, { q: 4, bag: "light_purple" }] };
challengeArray.push(dim_coral);
var clear_violet = { contains: [{ q: 5, bag: "plaid_olive" }, { q: 5, bag: "mirrored_violet" }, { q: 3, bag: "muted_lavender" }, { q: 2, bag: "clear_indigo" }] };
challengeArray.push(clear_violet);
var striped_coral = { contains: [{ q: 3, bag: "dim_fuchsia" }, { q: 5, bag: "vibrant_yellow" }, { q: 4, bag: "vibrant_plum" }, { q: 1, bag: "mirrored_turquoise" }] };
challengeArray.push(striped_coral);
var striped_gold = { contains: [{ q: 5, bag: "vibrant_blue" }, { q: 4, bag: "pale_blue" }, { q: 1, bag: "drab_beige" }, { q: 3, bag: "dotted_olive" }] };
challengeArray.push(striped_gold);
var dark_beige = { contains: [{ q: 1, bag: "wavy_gray" }] };
challengeArray.push(dark_beige);
var plaid_red = { contains: [{ q: 2, bag: "faded_gray" }, { q: 5, bag: "muted_olive" }, { q: 3, bag: "dark_silver" }] };
challengeArray.push(plaid_red);
var dark_purple = { contains: [{ q: 4, bag: "clear_maroon" }, { q: 3, bag: "dark_green" }] };
challengeArray.push(dark_purple);
var dull_yellow = { contains: [{ q: 3, bag: "vibrant_white" }, { q: 5, bag: "dull_indigo" }, { q: 4, bag: "dotted_teal" }] };
challengeArray.push(dull_yellow);
var faded_magenta = { contains: [{ q: 2, bag: "dark_violet" }, { q: 4, bag: "light_indigo" }] };
challengeArray.push(faded_magenta);
var pale_green = { contains: [{ q: 4, bag: "striped_fuchsia" }] };
challengeArray.push(pale_green);
var faded_blue = { contains: [{ q: 5, bag: "pale_chartreuse" }, { q: 5, bag: "plaid_indigo" }, { q: 5, bag: "posh_fuchsia" }] };
challengeArray.push(faded_blue);
var dim_brown = { contains: [{ q: 4, bag: "dim_magenta" }] };
challengeArray.push(dim_brown);
var pale_turquoise = { contains: [{ q: 3, bag: "bright_salmon" }, { q: 3, bag: "wavy_yellow" }] };
challengeArray.push(pale_turquoise);
var dark_coral = { contains: [{ q: 2, bag: "faded_beige" }, { q: 3, bag: "posh_gold" }, { q: 2, bag: "muted_cyan" }, { q: 3, bag: "dim_lime" }] };
challengeArray.push(dark_coral);
var striped_tan = { contains: [{ q: 3, bag: "vibrant_bronze" }] };
challengeArray.push(striped_tan);
var drab_gold = { contains: [{ q: 1, bag: "faded_cyan" }] };
challengeArray.push(drab_gold);
var dotted_green = { contains: [{ q: 1, bag: "dim_green" }, { q: 4, bag: "wavy_red" }] };
challengeArray.push(dotted_green);
var mirrored_salmon = { contains: [{ q: 1, bag: "posh_gray" }] };
challengeArray.push(mirrored_salmon);
var mirrored_olive = { contains: [{ q: 1, bag: "dotted_gold" }, { q: 2, bag: "vibrant_red" }] };
challengeArray.push(mirrored_olive);
var shiny_blue = { contains: [{ q: 2, bag: "clear_yellow" }] };
challengeArray.push(shiny_blue);
var dotted_white = { contains: [{ q: 1, bag: "wavy_blue" }, { q: 2, bag: "striped_beige" }, { q: 3, bag: "vibrant_black" }, { q: 5, bag: "striped_fuchsia" }] };
challengeArray.push(dotted_white);
var dotted_silver = { contains: [{ q: 4, bag: "dull_violet" }, { q: 3, bag: "clear_magenta" }] };
challengeArray.push(dotted_silver);
var muted_lime = { contains: [{ q: 5, bag: "bright_fuchsia" }, { q: 4, bag: "dim_violet" }] };
challengeArray.push(muted_lime);
var dim_white = { contains: [{ q: 4, bag: "wavy_plum" }, { q: 4, bag: "clear_coral" }, { q: 5, bag: "faded_lime" }] };
challengeArray.push(dim_white);
var striped_blue = { contains: [{ q: 2, bag: "striped_violet" }, { q: 5, bag: "clear_lime" }, { q: 4, bag: "muted_tan" }] };
challengeArray.push(striped_blue);
var dotted_fuchsia = { contains: [{ q: 3, bag: "pale_blue" }, { q: 5, bag: "wavy_blue" }, { q: 2, bag: "faded_maroon" }] };
challengeArray.push(dotted_fuchsia);
var dark_white = { contains: [{ q: 4, bag: "posh_fuchsia" }, { q: 5, bag: "dim_cyan" }] };
challengeArray.push(dark_white);
var pale_violet = { contains: [{ q: 5, bag: "plaid_fuchsia" }] };
challengeArray.push(pale_violet);
var muted_aqua = { contains: [{ q: 3, bag: "mirrored_tomato" }, { q: 2, bag: "dim_bronze" }, { q: 1, bag: "pale_purple" }, { q: 5, bag: "mirrored_aqua" }] };
challengeArray.push(muted_aqua);
var wavy_lime = { contains: [{ q: 1, bag: "vibrant_green" }, { q: 3, bag: "striped_tomato" }, { q: 5, bag: "dotted_beige" }, { q: 5, bag: "dark_plum" }] };
challengeArray.push(wavy_lime);
var dark_salmon = { contains: [{ q: 3, bag: "faded_plum" }, { q: 3, bag: "pale_blue" }, { q: 1, bag: "mirrored_red" }, { q: 3, bag: "striped_gold" }] };
challengeArray.push(dark_salmon);
var dotted_salmon = { contains: [{ q: 5, bag: "pale_crimson" }, { q: 3, bag: "dark_white" }, { q: 2, bag: "mirrored_beige" }, { q: 2, bag: "shiny_salmon" }] };
challengeArray.push(dotted_salmon);
var vibrant_white = { contains: [{ q: 4, bag: "dark_brown" }, { q: 1, bag: "faded_plum" }, { q: 1, bag: "plaid_red" }, { q: 1, bag: "dotted_lime" }] };
challengeArray.push(vibrant_white);
var muted_brown = { contains: [{ q: 3, bag: "plaid_violet" }] };
challengeArray.push(muted_brown);
var striped_red = { contains: [{ q: 4, bag: "plaid_bronze" }, { q: 5, bag: "bright_orange" }] };
challengeArray.push(striped_red);
var vibrant_teal = { contains: [{ q: 4, bag: "dull_olive" }, { q: 1, bag: "shiny_aqua" }, { q: 2, bag: "muted_olive" }] };
challengeArray.push(vibrant_teal);
var drab_green = { contains: [{ q: 2, bag: "muted_olive" }] };
challengeArray.push(drab_green);
var light_blue = { contains: [{ q: 1, bag: "muted_cyan" }, { q: 4, bag: "pale_teal" }, { q: 5, bag: "dotted_white" }, { q: 3, bag: "posh_gray" }] };
challengeArray.push(light_blue);
var light_gold = { contains: [{ q: 4, bag: "wavy_black" }, { q: 5, bag: "wavy_gray" }, { q: 4, bag: "pale_teal" }, { q: 4, bag: "pale_violet" }] };
challengeArray.push(light_gold);
var posh_violet = { contains: [{ q: 5, bag: "shiny_magenta" }, { q: 4, bag: "dark_white" }, { q: 4, bag: "posh_lime" }, { q: 4, bag: "plaid_silver" }] };
challengeArray.push(posh_violet);
var striped_silver = { contains: [{ q: 3, bag: "pale_crimson" }, { q: 4, bag: "posh_lime" }, { q: 3, bag: "dim_bronze" }] };
challengeArray.push(striped_silver);
var dull_tomato = { contains: [{ q: 4, bag: "plaid_lime" }, { q: 3, bag: "striped_lavender" }, { q: 4, bag: "clear_turquoise" }, { q: 3, bag: "dull_lime" }] };
challengeArray.push(dull_tomato);
var dull_blue = { contains: [{ q: 2, bag: "muted_tan" }, { q: 4, bag: "posh_brown" }, { q: 2, bag: "vibrant_beige" }] };
challengeArray.push(dull_blue);
var light_magenta = { contains: [{ q: 5, bag: "drab_salmon" }, { q: 1, bag: "bright_red" }] };
challengeArray.push(light_magenta);
var dotted_teal = { contains: [{ q: 2, bag: "pale_yellow" }, { q: 3, bag: "posh_red" }, { q: 2, bag: "drab_aqua" }, { q: 1, bag: "muted_indigo" }] };
challengeArray.push(dotted_teal);
var light_beige = { contains: [{ q: 1, bag: "drab_fuchsia" }] };
challengeArray.push(light_beige);
var muted_fuchsia = { contains: [{ q: 2, bag: "shiny_cyan" }, { q: 4, bag: "bright_chartreuse" }, { q: 2, bag: "striped_indigo" }] };
challengeArray.push(muted_fuchsia);
var muted_gray = { contains: [{ q: 2, bag: "vibrant_brown" }, { q: 5, bag: "clear_violet" }] };
challengeArray.push(muted_gray);
var bright_maroon = { contains: [{ q: 4, bag: "dark_indigo" }, { q: 5, bag: "plaid_olive" }] };
challengeArray.push(bright_maroon);
var wavy_tomato = { contains: [{ q: 3, bag: "vibrant_gray" }] };
challengeArray.push(wavy_tomato);
var dim_purple = { contains: [{ q: 3, bag: "dull_lime" }] };
challengeArray.push(dim_purple);
var mirrored_blue = { contains: [{ q: 3, bag: "pale_aqua" }] };
challengeArray.push(mirrored_blue);
var drab_crimson = { contains: [{ q: 2, bag: "muted_brown" }, { q: 1, bag: "faded_fuchsia" }] };
challengeArray.push(drab_crimson);
var muted_turquoise = { contains: [{ q: 1, bag: "dull_olive" }, { q: 5, bag: "dull_silver" }, { q: 1, bag: "vibrant_gray" }, { q: 4, bag: "plaid_violet" }] };
challengeArray.push(muted_turquoise);
var posh_lime = { contains: [{ q: 1, bag: "pale_purple" }, { q: 1, bag: "vibrant_black" }, { q: 3, bag: "clear_green" }] };
challengeArray.push(posh_lime);
var light_lavender = { contains: [{ q: 5, bag: "vibrant_lime" }, { q: 1, bag: "light_coral" }] };
challengeArray.push(light_lavender);
var striped_maroon = { contains: [{ q: 3, bag: "wavy_yellow" }, { q: 3, bag: "faded_silver" }, { q: 5, bag: "dim_olive" }, { q: 3, bag: "muted_tan" }] };
challengeArray.push(striped_maroon);
var shiny_olive = { contains: [{ q: 2, bag: "bright_olive" }] };
challengeArray.push(shiny_olive);
var mirrored_fuchsia = { contains: [{ q: 3, bag: "dim_gray" }] };
challengeArray.push(mirrored_fuchsia);
var drab_blue = { contains: [{ q: 2, bag: "light_salmon" }, { q: 3, bag: "muted_olive" }, { q: 1, bag: "dark_black" }] };
challengeArray.push(drab_blue);
var drab_magenta = { contains: [{ q: 4, bag: "light_yellow" }, { q: 2, bag: "muted_aqua" }, { q: 5, bag: "vibrant_magenta" }, { q: 4, bag: "vibrant_silver" }] };
challengeArray.push(drab_magenta);
var light_cyan = { contains: [{ q: 1, bag: "dull_chartreuse" }, { q: 1, bag: "dim_bronze" }] };
challengeArray.push(light_cyan);
var plaid_lime = { contains: [{ q: 1, bag: "muted_white" }, { q: 2, bag: "striped_fuchsia" }, { q: 5, bag: "vibrant_gray" }] };
challengeArray.push(plaid_lime);
var wavy_tan = { contains: [{ q: 4, bag: "dotted_beige" }, { q: 4, bag: "striped_cyan" }, { q: 4, bag: "light_salmon" }, { q: 2, bag: "shiny_gray" }] };
challengeArray.push(wavy_tan);
var faded_yellow = { contains: [{ q: 1, bag: "bright_teal" }, { q: 1, bag: "striped_salmon" }, { q: 4, bag: "striped_plum" }, { q: 5, bag: "drab_orange" }] };
challengeArray.push(faded_yellow);
var shiny_silver = { contains: [{ q: 2, bag: "vibrant_green" }] };
challengeArray.push(shiny_silver);
var mirrored_aqua = { contains: [{ q: 4, bag: "vibrant_black" }, { q: 2, bag: "faded_coral" }, { q: 1, bag: "bright_tomato" }, { q: 1, bag: "pale_purple" }] };
challengeArray.push(mirrored_aqua);
var dark_tomato = { contains: [{ q: 4, bag: "drab_beige" }, { q: 5, bag: "bright_gray" }, { q: 5, bag: "shiny_teal" }, { q: 1, bag: "pale_blue" }] };
challengeArray.push(dark_tomato);
var pale_coral = { contains: [{ q: 5, bag: "striped_orange" }, { q: 4, bag: "muted_red" }] };
challengeArray.push(pale_coral);
var mirrored_coral = { contains: [{ q: 4, bag: "plaid_olive" }, { q: 1, bag: "faded_indigo" }] };
challengeArray.push(mirrored_coral);
var shiny_violet = { contains: [{ q: 5, bag: "bright_tomato" }] };
challengeArray.push(shiny_violet);
var posh_beige = { contains: [{ q: 2, bag: "dim_brown" }] };
challengeArray.push(posh_beige);
var dull_crimson = { contains: [{ q: 3, bag: "mirrored_chartreuse" }, { q: 1, bag: "shiny_teal" }, { q: 3, bag: "shiny_cyan" }] };
challengeArray.push(dull_crimson);
var drab_lavender = { contains: [{ q: 1, bag: "shiny_tomato" }, { q: 5, bag: "posh_cyan" }] };
challengeArray.push(drab_lavender);
var clear_lavender = { contains: [{ q: 1, bag: "bright_fuchsia" }, { q: 1, bag: "pale_crimson" }] };
challengeArray.push(clear_lavender);
var wavy_fuchsia = { contains: [{ q: 5, bag: "wavy_tomato" }, { q: 5, bag: "wavy_bronze" }, { q: 5, bag: "mirrored_tomato" }] };
challengeArray.push(wavy_fuchsia);
var faded_turquoise = { contains: [{ q: 3, bag: "muted_crimson" }, { q: 3, bag: "pale_crimson" }, { q: 4, bag: "drab_gray" }, { q: 1, bag: "dull_white" }] };
challengeArray.push(faded_turquoise);
var pale_blue = { contains: [{ q: 1, bag: "shiny_gold" }, { q: 5, bag: "dull_silver" }, { q: 5, bag: "posh_lime" }] };
challengeArray.push(pale_blue);
var dim_beige = { contains: [{ q: 1, bag: "vibrant_red" }] };
challengeArray.push(dim_beige);
var bright_tomato = { contains: [{ q: 2, bag: "dull_olive" }, { q: 1, bag: "dim_crimson" }, { q: 5, bag: "faded_salmon" }] };
challengeArray.push(bright_tomato);
var pale_gold = { contains: [{ q: 2, bag: "dark_blue" }] };
challengeArray.push(pale_gold);
var muted_tomato = { contains: [{ q: 5, bag: "mirrored_blue" }, { q: 1, bag: "dull_crimson" }, { q: 4, bag: "mirrored_cyan" }, { q: 4, bag: "wavy_blue" }] };
challengeArray.push(muted_tomato);
var wavy_beige = { contains: [{ q: 2, bag: "wavy_lime" }, { q: 3, bag: "dotted_salmon" }] };
challengeArray.push(wavy_beige);
var dotted_violet = { contains: [{ q: 5, bag: "bright_orange" }, { q: 5, bag: "posh_olive" }, { q: 3, bag: "dark_violet" }] };
challengeArray.push(dotted_violet);
var vibrant_black = { contains: [{ q: 4, bag: "bright_chartreuse" }] };
challengeArray.push(vibrant_black);
var light_olive = { contains: [{ q: 1, bag: "dotted_yellow" }, { q: 5, bag: "shiny_coral" }, { q: 1, bag: "drab_green" }, { q: 2, bag: "vibrant_lime" }] };
challengeArray.push(light_olive);
var plaid_crimson = { contains: [{ q: 3, bag: "shiny_fuchsia" }] };
challengeArray.push(plaid_crimson);
var mirrored_yellow = { contains: [{ q: 1, bag: "shiny_red" }, { q: 2, bag: "muted_lime" }] };
challengeArray.push(mirrored_yellow);
var pale_tan = { contains: [{ q: 2, bag: "pale_crimson" }, { q: 4, bag: "pale_green" }] };
challengeArray.push(pale_tan);
var pale_yellow = { contains: [{ q: 1, bag: "clear_maroon" }, { q: 5, bag: "wavy_silver" }, { q: 4, bag: "faded_purple" }, { q: 4, bag: "faded_plum" }] };
challengeArray.push(pale_yellow);
var mirrored_silver = { contains: [{ q: 5, bag: "pale_lavender" }, { q: 5, bag: "clear_orange" }, { q: 4, bag: "faded_lime" }] };
challengeArray.push(mirrored_silver);
var drab_tomato = { contains: [{ q: 2, bag: "dull_lavender" }] };
challengeArray.push(drab_tomato);
var drab_bronze = { contains: [{ q: 5, bag: "shiny_indigo" }, { q: 3, bag: "pale_purple" }] };
challengeArray.push(drab_bronze);
var muted_salmon = { contains: [{ q: 2, bag: "clear_green" }, { q: 4, bag: "faded_coral" }, { q: 1, bag: "faded_salmon" }] };
challengeArray.push(muted_salmon);
var posh_brown = { contains: [{ q: 2, bag: "vibrant_magenta" }, { q: 1, bag: "muted_salmon" }] };
challengeArray.push(posh_brown);
var striped_magenta = { contains: [{ q: 2, bag: "shiny_white" }] };
challengeArray.push(striped_magenta);
var drab_teal = { contains: [{ q: 1, bag: "vibrant_red" }, { q: 5, bag: "striped_violet" }, { q: 1, bag: "muted_olive" }] };
challengeArray.push(drab_teal);
var mirrored_red = { contains: [{ q: 4, bag: "bright_chartreuse" }] };
challengeArray.push(mirrored_red);
var muted_magenta = { contains: [{ q: 4, bag: "dotted_blue" }, { q: 2, bag: "light_bronze" }] };
challengeArray.push(muted_magenta);
var clear_orange = { contains: [{ q: 4, bag: "striped_cyan" }] };
challengeArray.push(clear_orange);
var dotted_maroon = { contains: [{ q: 1, bag: "plaid_olive" }] };
challengeArray.push(dotted_maroon);
var mirrored_white = { contains: [{ q: 1, bag: "shiny_tomato" }, { q: 1, bag: "plaid_lime" }] };
challengeArray.push(mirrored_white);
var mirrored_tomato = { contains: [{ q: 5, bag: "pale_brown" }, { q: 4, bag: "clear_green" }, { q: 4, bag: "mirrored_chartreuse" }] };
challengeArray.push(mirrored_tomato);
var bright_magenta = { contains: [{ q: 3, bag: "bright_salmon" }, { q: 4, bag: "posh_fuchsia" }, { q: 3, bag: "dotted_tan" }] };
challengeArray.push(bright_magenta);
var plaid_salmon = { contains: [{ q: 2, bag: "bright_white" }, { q: 5, bag: "mirrored_lime" }] };
challengeArray.push(plaid_salmon);
var pale_black = { contains: [{ q: 2, bag: "faded_tomato" }, { q: 3, bag: "dotted_brown" }, { q: 2, bag: "faded_turquoise" }] };
challengeArray.push(pale_black);
var posh_gray = { contains: [{ q: 2, bag: "mirrored_chartreuse" }] };
challengeArray.push(posh_gray);
var muted_beige = { contains: [{ q: 3, bag: "posh_lime" }, { q: 5, bag: "wavy_plum" }, { q: 2, bag: "light_crimson" }, { q: 2, bag: "pale_purple" }] };
challengeArray.push(muted_beige);
var pale_red = { contains: [{ q: 3, bag: "pale_beige" }, { q: 2, bag: "vibrant_yellow" }] };
challengeArray.push(pale_red);
var bright_indigo = { contains: [{ q: 5, bag: "mirrored_violet" }, { q: 4, bag: "mirrored_tomato" }, { q: 3, bag: "clear_lavender" }, { q: 1, bag: "muted_gold" }] };
challengeArray.push(bright_indigo);
var shiny_teal = { contains: [] };
challengeArray.push(shiny_teal);
var drab_plum = { contains: [{ q: 5, bag: "mirrored_chartreuse" }, { q: 1, bag: "light_brown" }] };
challengeArray.push(drab_plum);
var clear_tomato = { contains: [{ q: 4, bag: "faded_coral" }] };
challengeArray.push(clear_tomato);
var light_aqua = { contains: [{ q: 5, bag: "bright_fuchsia" }, { q: 4, bag: "posh_red" }, { q: 2, bag: "light_gray" }, { q: 2, bag: "bright_tomato" }] };
challengeArray.push(light_aqua);
var shiny_tomato = { contains: [{ q: 5, bag: "muted_turquoise" }] };
challengeArray.push(shiny_tomato);
var dull_olive = { contains: [] };
challengeArray.push(dull_olive);
var dim_chartreuse = { contains: [{ q: 4, bag: "posh_aqua" }] };
challengeArray.push(dim_chartreuse);
var bright_turquoise = { contains: [{ q: 4, bag: "pale_olive" }] };
challengeArray.push(bright_turquoise);
var pale_aqua = { contains: [{ q: 3, bag: "muted_aqua" }, { q: 5, bag: "shiny_plum" }, { q: 3, bag: "striped_indigo" }, { q: 5, bag: "pale_blue" }] };
challengeArray.push(pale_aqua);
var shiny_indigo = { contains: [{ q: 1, bag: "posh_tan" }, { q: 3, bag: "dotted_teal" }] };
challengeArray.push(shiny_indigo);
var faded_salmon = { contains: [] };
challengeArray.push(faded_salmon);
var dark_magenta = { contains: [{ q: 2, bag: "striped_plum" }, { q: 1, bag: "dull_brown" }, { q: 2, bag: "wavy_tan" }, { q: 2, bag: "faded_olive" }] };
challengeArray.push(dark_magenta);
var vibrant_silver = { contains: [{ q: 5, bag: "wavy_tomato" }, { q: 3, bag: "dull_chartreuse" }, { q: 3, bag: "posh_lime" }, { q: 2, bag: "dull_violet" }] };
challengeArray.push(vibrant_silver);
var wavy_violet = { contains: [{ q: 1, bag: "dim_crimson" }, { q: 5, bag: "drab_white" }, { q: 2, bag: "drab_purple" }] };
challengeArray.push(wavy_violet);
var dull_green = { contains: [{ q: 1, bag: "posh_red" }, { q: 5, bag: "shiny_teal" }] };
challengeArray.push(dull_green);
var posh_tan = { contains: [{ q: 4, bag: "pale_yellow" }, { q: 1, bag: "dim_beige" }, { q: 1, bag: "shiny_tomato" }] };
challengeArray.push(posh_tan);
var shiny_purple = { contains: [{ q: 4, bag: "shiny_lavender" }, { q: 2, bag: "plaid_violet" }, { q: 2, bag: "drab_beige" }, { q: 2, bag: "pale_blue" }] };
challengeArray.push(shiny_purple);
var plaid_lavender = { contains: [{ q: 3, bag: "faded_purple" }, { q: 1, bag: "wavy_purple" }] };
challengeArray.push(plaid_lavender);
var dotted_lime = { contains: [{ q: 5, bag: "muted_white" }, { q: 2, bag: "posh_olive" }, { q: 2, bag: "pale_crimson" }, { q: 5, bag: "dark_plum" }] };
challengeArray.push(dotted_lime);
var shiny_brown = { contains: [{ q: 3, bag: "pale_tan" }, { q: 5, bag: "shiny_green" }, { q: 4, bag: "vibrant_brown" }] };
challengeArray.push(shiny_brown);
var clear_gold = { contains: [{ q: 4, bag: "striped_plum" }, { q: 1, bag: "bright_fuchsia" }, { q: 3, bag: "faded_salmon" }] };
challengeArray.push(clear_gold);
var drab_cyan = { contains: [{ q: 2, bag: "muted_purple" }, { q: 2, bag: "dull_aqua" }, { q: 3, bag: "shiny_gray" }] };
challengeArray.push(drab_cyan);
var dark_violet = { contains: [{ q: 1, bag: "plaid_salmon" }, { q: 3, bag: "vibrant_salmon" }] };
challengeArray.push(dark_violet);
var shiny_aqua = { contains: [{ q: 3, bag: "mirrored_tomato" }] };
challengeArray.push(shiny_aqua);
var dotted_blue = { contains: [{ q: 3, bag: "clear_white" }, { q: 4, bag: "dull_chartreuse" }, { q: 2, bag: "light_cyan" }] };
challengeArray.push(dotted_blue);
var dull_beige = { contains: [{ q: 2, bag: "vibrant_red" }, { q: 5, bag: "muted_olive" }] };
challengeArray.push(dull_beige);
var wavy_blue = { contains: [{ q: 2, bag: "dark_brown" }] };
challengeArray.push(wavy_blue);
var wavy_aqua = { contains: [{ q: 4, bag: "wavy_teal" }, { q: 5, bag: "muted_maroon" }, { q: 3, bag: "faded_gray" }, { q: 5, bag: "plaid_blue" }] };
challengeArray.push(wavy_aqua);
var dull_brown = { contains: [{ q: 5, bag: "posh_olive" }, { q: 2, bag: "striped_violet" }, { q: 4, bag: "mirrored_lime" }] };
challengeArray.push(dull_brown);
var striped_salmon = { contains: [{ q: 4, bag: "faded_coral" }, { q: 5, bag: "vibrant_blue" }, { q: 4, bag: "shiny_magenta" }, { q: 3, bag: "plaid_red" }] };
challengeArray.push(striped_salmon);
var mirrored_maroon = { contains: [{ q: 1, bag: "mirrored_lime" }, { q: 2, bag: "wavy_salmon" }, { q: 2, bag: "wavy_cyan" }] };
challengeArray.push(mirrored_maroon);
var clear_magenta = { contains: [{ q: 1, bag: "vibrant_black" }, { q: 3, bag: "vibrant_coral" }] };
challengeArray.push(clear_magenta);
var clear_salmon = { contains: [{ q: 5, bag: "bright_plum" }, { q: 5, bag: "light_beige" }, { q: 2, bag: "plaid_aqua" }] };
challengeArray.push(clear_salmon);
var bright_yellow = { contains: [{ q: 5, bag: "striped_green" }, { q: 3, bag: "muted_violet" }] };
challengeArray.push(bright_yellow);
var dim_crimson = { contains: [{ q: 4, bag: "dull_olive" }, { q: 1, bag: "faded_coral" }, { q: 3, bag: "clear_green" }, { q: 4, bag: "pale_purple" }] };
challengeArray.push(dim_crimson);
var light_violet = { contains: [{ q: 2, bag: "shiny_indigo" }, { q: 1, bag: "clear_maroon" }, { q: 2, bag: "dull_blue" }] };
challengeArray.push(light_violet);
var drab_coral = { contains: [{ q: 2, bag: "posh_blue" }, { q: 1, bag: "dim_lime" }, { q: 3, bag: "shiny_turquoise" }, { q: 3, bag: "faded_fuchsia" }] };
challengeArray.push(drab_coral);
var plaid_bronze = { contains: [{ q: 2, bag: "vibrant_teal" }] };
challengeArray.push(plaid_bronze);
var dull_magenta = { contains: [{ q: 4, bag: "dull_tan" }, { q: 4, bag: "plaid_yellow" }, { q: 2, bag: "dim_turquoise" }] };
challengeArray.push(dull_magenta);
var plaid_tan = { contains: [{ q: 1, bag: "mirrored_maroon" }, { q: 5, bag: "muted_maroon" }] };
challengeArray.push(plaid_tan);
var shiny_maroon = { contains: [{ q: 1, bag: "shiny_coral" }, { q: 5, bag: "dotted_tomato" }] };
challengeArray.push(shiny_maroon);
var faded_bronze = { contains: [{ q: 5, bag: "bright_purple" }, { q: 4, bag: "vibrant_tomato" }] };
challengeArray.push(faded_bronze);
var pale_magenta = { contains: [{ q: 3, bag: "vibrant_green" }, { q: 3, bag: "dotted_olive" }] };
challengeArray.push(pale_magenta);
var dark_blue = { contains: [{ q: 3, bag: "dull_gray" }] };
challengeArray.push(dark_blue);
var dim_teal = { contains: [{ q: 1, bag: "dotted_plum" }, { q: 3, bag: "faded_olive" }, { q: 4, bag: "dotted_orange" }] };
challengeArray.push(dim_teal);
var faded_crimson = { contains: [{ q: 3, bag: "vibrant_violet" }, { q: 4, bag: "wavy_plum" }, { q: 1, bag: "wavy_coral" }, { q: 1, bag: "vibrant_lime" }] };
challengeArray.push(faded_crimson);
var dotted_black = { contains: [{ q: 2, bag: "striped_purple" }] };
challengeArray.push(dotted_black);
var mirrored_indigo = { contains: [{ q: 4, bag: "wavy_cyan" }, { q: 3, bag: "dull_gold" }, { q: 1, bag: "dull_lime" }] };
challengeArray.push(mirrored_indigo);
var muted_lavender = { contains: [{ q: 5, bag: "striped_silver" }, { q: 2, bag: "posh_brown" }] };
challengeArray.push(muted_lavender);
var mirrored_lavender = { contains: [{ q: 1, bag: "pale_lime" }, { q: 2, bag: "drab_olive" }, { q: 1, bag: "wavy_green" }] };
challengeArray.push(mirrored_lavender);
var drab_lime = { contains: [{ q: 2, bag: "faded_plum" }, { q: 3, bag: "muted_purple" }, { q: 1, bag: "faded_teal" }, { q: 2, bag: "vibrant_plum" }] };
challengeArray.push(drab_lime);
var bright_blue = { contains: [{ q: 3, bag: "drab_aqua" }, { q: 4, bag: "striped_tomato" }] };
challengeArray.push(bright_blue);
var drab_purple = { contains: [{ q: 2, bag: "faded_purple" }, { q: 4, bag: "shiny_turquoise" }, { q: 5, bag: "dark_black" }, { q: 1, bag: "pale_plum" }] };
challengeArray.push(drab_purple);
var mirrored_chartreuse = { contains: [{ q: 4, bag: "clear_green" }] };
challengeArray.push(mirrored_chartreuse);
var wavy_gold = { contains: [{ q: 1, bag: "plaid_olive" }, { q: 5, bag: "drab_teal" }, { q: 5, bag: "dotted_salmon" }, { q: 2, bag: "dull_tan" }] };
challengeArray.push(wavy_gold);
var shiny_green = { contains: [{ q: 1, bag: "dim_crimson" }, { q: 1, bag: "dotted_olive" }] };
challengeArray.push(shiny_green);
var plaid_tomato = { contains: [{ q: 1, bag: "clear_gold" }] };
challengeArray.push(plaid_tomato);
var striped_chartreuse = { contains: [{ q: 5, bag: "muted_lavender" }, { q: 5, bag: "plaid_white" }] };
challengeArray.push(striped_chartreuse);
var vibrant_violet = { contains: [{ q: 1, bag: "shiny_cyan" }, { q: 5, bag: "drab_magenta" }, { q: 5, bag: "drab_olive" }] };
challengeArray.push(vibrant_violet);
var vibrant_gray = { contains: [{ q: 2, bag: "vibrant_black" }, { q: 5, bag: "pale_purple" }] };
challengeArray.push(vibrant_gray);
var striped_plum = { contains: [{ q: 1, bag: "mirrored_chartreuse" }] };
challengeArray.push(striped_plum);
var mirrored_brown = { contains: [{ q: 5, bag: "light_plum" }, { q: 2, bag: "dark_blue" }, { q: 5, bag: "shiny_aqua" }, { q: 3, bag: "vibrant_turquoise" }] };
challengeArray.push(mirrored_brown);
var posh_crimson = { contains: [{ q: 4, bag: "striped_orange" }, { q: 3, bag: "wavy_salmon" }, { q: 4, bag: "dull_cyan" }] };
challengeArray.push(posh_crimson);
var plaid_purple = { contains: [{ q: 1, bag: "dotted_beige" }, { q: 4, bag: "shiny_teal" }, { q: 4, bag: "wavy_magenta" }, { q: 5, bag: "pale_chartreuse" }] };
challengeArray.push(plaid_purple);
var clear_purple = { contains: [{ q: 1, bag: "faded_purple" }] };
challengeArray.push(clear_purple);
var plaid_brown = { contains: [{ q: 5, bag: "light_brown" }, { q: 5, bag: "drab_fuchsia" }, { q: 1, bag: "clear_bronze" }, { q: 2, bag: "dark_black" }] };
challengeArray.push(plaid_brown);
var dim_violet = { contains: [{ q: 2, bag: "bright_lavender" }, { q: 4, bag: "muted_indigo" }, { q: 1, bag: "bright_white" }] };
challengeArray.push(dim_violet);
var plaid_fuchsia = { contains: [{ q: 3, bag: "muted_olive" }, { q: 2, bag: "clear_olive" }] };
challengeArray.push(plaid_fuchsia);
var posh_white = { contains: [{ q: 3, bag: "dull_aqua" }, { q: 2, bag: "striped_silver" }] };
challengeArray.push(posh_white);
var dotted_gray = { contains: [{ q: 2, bag: "vibrant_orange" }, { q: 3, bag: "muted_salmon" }] };
challengeArray.push(dotted_gray);
var clear_silver = { contains: [{ q: 1, bag: "faded_indigo" }, { q: 1, bag: "dim_violet" }] };
challengeArray.push(clear_silver);
var dull_fuchsia = { contains: [{ q: 1, bag: "vibrant_turquoise" }] };
challengeArray.push(dull_fuchsia);
var shiny_lime = { contains: [{ q: 2, bag: "wavy_teal" }, { q: 1, bag: "clear_blue" }] };
challengeArray.push(shiny_lime);
var bright_gold = { contains: [{ q: 2, bag: "dotted_gray" }, { q: 3, bag: "dark_yellow" }, { q: 3, bag: "light_yellow" }, { q: 4, bag: "faded_maroon" }] };
challengeArray.push(bright_gold);
var dark_teal = { contains: [{ q: 5, bag: "light_crimson" }, { q: 5, bag: "clear_orange" }, { q: 4, bag: "vibrant_magenta" }] };
challengeArray.push(dark_teal);
var drab_black = { contains: [{ q: 3, bag: "clear_green" }] };
challengeArray.push(drab_black);
var light_silver = { contains: [{ q: 2, bag: "clear_black" }] };
challengeArray.push(light_silver);
var striped_cyan = { contains: [{ q: 4, bag: "clear_lavender" }, { q: 1, bag: "faded_salmon" }, { q: 4, bag: "faded_plum" }, { q: 3, bag: "shiny_teal" }] };
challengeArray.push(striped_cyan);
var plaid_yellow = { contains: [{ q: 5, bag: "shiny_teal" }] };
challengeArray.push(plaid_yellow);
var mirrored_turquoise = { contains: [{ q: 1, bag: "dull_chartreuse" }] };
challengeArray.push(mirrored_turquoise);
var shiny_yellow = { contains: [{ q: 5, bag: "dotted_crimson" }] };
challengeArray.push(shiny_yellow);
var vibrant_yellow = { contains: [{ q: 2, bag: "striped_beige" }, { q: 5, bag: "dark_white" }] };
challengeArray.push(vibrant_yellow);
var faded_violet = { contains: [{ q: 4, bag: "drab_tan" }] };
challengeArray.push(faded_violet);
var plaid_orange = { contains: [{ q: 2, bag: "dim_crimson" }, { q: 1, bag: "faded_cyan" }, { q: 4, bag: "mirrored_cyan" }, { q: 1, bag: "bright_indigo" }] };
challengeArray.push(plaid_orange);
var muted_coral = { contains: [{ q: 2, bag: "faded_lime" }, { q: 1, bag: "plaid_blue" }, { q: 5, bag: "posh_white" }] };
challengeArray.push(muted_coral);
var faded_lime = { contains: [{ q: 5, bag: "wavy_lavender" }, { q: 5, bag: "muted_green" }, { q: 3, bag: "shiny_beige" }, { q: 4, bag: "wavy_lime" }] };
challengeArray.push(faded_lime);
var pale_crimson = { contains: [{ q: 3, bag: "mirrored_chartreuse" }] };
challengeArray.push(pale_crimson);
var dull_teal = { contains: [{ q: 4, bag: "clear_blue" }, { q: 2, bag: "mirrored_red" }, { q: 4, bag: "posh_turquoise" }, { q: 2, bag: "drab_black" }] };
challengeArray.push(dull_teal);
var clear_teal = { contains: [{ q: 4, bag: "clear_brown" }, { q: 4, bag: "mirrored_fuchsia" }] };
challengeArray.push(clear_teal);
var drab_fuchsia = { contains: [{ q: 2, bag: "mirrored_black" }, { q: 5, bag: "plaid_silver" }, { q: 4, bag: "drab_tan" }] };
challengeArray.push(drab_fuchsia);
var dotted_purple = { contains: [{ q: 5, bag: "faded_red" }, { q: 5, bag: "dull_bronze" }] };
challengeArray.push(dotted_purple);
var mirrored_cyan = { contains: [{ q: 4, bag: "clear_green" }, { q: 5, bag: "muted_cyan" }, { q: 3, bag: "dull_violet" }, { q: 5, bag: "vibrant_yellow" }] };
challengeArray.push(mirrored_cyan);
var pale_white = { contains: [{ q: 1, bag: "vibrant_green" }, { q: 2, bag: "wavy_magenta" }, { q: 5, bag: "dotted_olive" }, { q: 5, bag: "drab_magenta" }] };
challengeArray.push(pale_white);
var faded_red = { contains: [{ q: 5, bag: "posh_turquoise" }, { q: 3, bag: "dotted_gold" }, { q: 5, bag: "light_salmon" }, { q: 5, bag: "faded_bronze" }] };
challengeArray.push(faded_red);
var posh_plum = { contains: [{ q: 1, bag: "shiny_brown" }, { q: 2, bag: "vibrant_silver" }, { q: 1, bag: "bright_beige" }, { q: 1, bag: "clear_maroon" }] };
challengeArray.push(posh_plum);
var dotted_tan = { contains: [{ q: 2, bag: "pale_bronze" }, { q: 3, bag: "drab_tan" }] };
challengeArray.push(dotted_tan);
var dark_cyan = { contains: [{ q: 5, bag: "wavy_fuchsia" }, { q: 3, bag: "posh_beige" }] };
challengeArray.push(dark_cyan);
var clear_gray = { contains: [{ q: 2, bag: "muted_silver" }, { q: 4, bag: "drab_violet" }] };
challengeArray.push(clear_gray);
var faded_aqua = { contains: [{ q: 5, bag: "vibrant_green" }, { q: 3, bag: "dim_crimson" }] };
challengeArray.push(faded_aqua);
var vibrant_indigo = { contains: [{ q: 1, bag: "drab_violet" }, { q: 3, bag: "dull_gray" }, { q: 4, bag: "wavy_lavender" }, { q: 2, bag: "shiny_fuchsia" }] };
challengeArray.push(vibrant_indigo);
var posh_red = { contains: [{ q: 1, bag: "clear_magenta" }, { q: 2, bag: "pale_bronze" }] };
challengeArray.push(posh_red);
var clear_turquoise = { contains: [{ q: 1, bag: "plaid_magenta" }, { q: 4, bag: "dotted_tan" }] };
challengeArray.push(clear_turquoise);
var mirrored_plum = { contains: [{ q: 3, bag: "plaid_purple" }, { q: 3, bag: "dull_bronze" }, { q: 3, bag: "pale_olive" }] };
challengeArray.push(mirrored_plum);
var bright_salmon = { contains: [{ q: 2, bag: "mirrored_chartreuse" }, { q: 3, bag: "pale_brown" }, { q: 5, bag: "faded_plum" }, { q: 1, bag: "striped_cyan" }] };
challengeArray.push(bright_salmon);
var clear_black = { contains: [{ q: 4, bag: "mirrored_fuchsia" }, { q: 5, bag: "dim_bronze" }, { q: 2, bag: "drab_violet" }] };
challengeArray.push(clear_black);
var striped_indigo = { contains: [{ q: 1, bag: "vibrant_black" }, { q: 1, bag: "striped_fuchsia" }, { q: 4, bag: "shiny_gray" }, { q: 5, bag: "clear_orange" }] };
challengeArray.push(striped_indigo);
var wavy_teal = { contains: [{ q: 4, bag: "striped_lime" }] };
challengeArray.push(wavy_teal);
var striped_white = { contains: [{ q: 4, bag: "wavy_lime" }, { q: 3, bag: "clear_magenta" }, { q: 3, bag: "dull_lavender" }] };
challengeArray.push(striped_white);
var clear_fuchsia = { contains: [{ q: 2, bag: "faded_brown" }, { q: 3, bag: "shiny_coral" }, { q: 1, bag: "vibrant_blue" }, { q: 1, bag: "posh_silver" }] };
challengeArray.push(clear_fuchsia);
var muted_blue = { contains: [{ q: 3, bag: "pale_fuchsia" }, { q: 5, bag: "posh_fuchsia" }, { q: 2, bag: "dim_magenta" }, { q: 1, bag: "wavy_lavender" }] };
challengeArray.push(muted_blue);
var pale_brown = { contains: [] };
challengeArray.push(pale_brown);
var posh_fuchsia = { contains: [{ q: 2, bag: "dim_crimson" }, { q: 5, bag: "dull_chartreuse" }, { q: 4, bag: "dim_bronze" }, { q: 5, bag: "vibrant_orange" }] };
challengeArray.push(posh_fuchsia);
var wavy_salmon = { contains: [{ q: 4, bag: "vibrant_black" }] };
challengeArray.push(wavy_salmon);
var clear_aqua = { contains: [{ q: 2, bag: "clear_tan" }, { q: 3, bag: "dim_gray" }, { q: 1, bag: "bright_lavender" }] };
challengeArray.push(clear_aqua);
var light_green = { contains: [{ q: 5, bag: "dim_tan" }, { q: 3, bag: "shiny_chartreuse" }, { q: 4, bag: "bright_crimson" }] };
challengeArray.push(light_green);
var wavy_yellow = { contains: [{ q: 4, bag: "pale_brown" }] };
challengeArray.push(wavy_yellow);
var dull_indigo = { contains: [{ q: 3, bag: "plaid_lime" }, { q: 5, bag: "wavy_silver" }, { q: 4, bag: "vibrant_coral" }, { q: 3, bag: "mirrored_tomato" }] };
challengeArray.push(dull_indigo);
var dim_plum = { contains: [{ q: 4, bag: "dotted_magenta" }, { q: 5, bag: "dim_crimson" }, { q: 3, bag: "wavy_blue" }, { q: 4, bag: "mirrored_black" }] };
challengeArray.push(dim_plum);
var dull_gold = { contains: [{ q: 5, bag: "bright_lavender" }, { q: 2, bag: "vibrant_magenta" }, { q: 4, bag: "dull_lavender" }] };
challengeArray.push(dull_gold);
var plaid_plum = { contains: [{ q: 2, bag: "muted_cyan" }, { q: 3, bag: "shiny_purple" }, { q: 2, bag: "drab_olive" }] };
challengeArray.push(plaid_plum);
var pale_lavender = { contains: [{ q: 1, bag: "vibrant_magenta" }, { q: 3, bag: "mirrored_violet" }, { q: 1, bag: "vibrant_green" }, { q: 2, bag: "faded_purple" }] };
challengeArray.push(pale_lavender);
var drab_indigo = { contains: [{ q: 1, bag: "vibrant_lavender" }, { q: 4, bag: "drab_aqua" }] };
challengeArray.push(drab_indigo);
var dotted_olive = { contains: [{ q: 3, bag: "faded_plum" }, { q: 5, bag: "wavy_plum" }, { q: 1, bag: "pale_brown" }] };
challengeArray.push(dotted_olive);
var dotted_beige = { contains: [{ q: 5, bag: "bright_tomato" }, { q: 4, bag: "pale_purple" }, { q: 4, bag: "dim_crimson" }, { q: 4, bag: "dull_gold" }] };
challengeArray.push(dotted_beige);
var clear_coral = { contains: [{ q: 1, bag: "dark_teal" }, { q: 2, bag: "bright_purple" }, { q: 4, bag: "clear_blue" }, { q: 4, bag: "pale_orange" }] };
challengeArray.push(clear_coral);
var light_bronze = { contains: [{ q: 4, bag: "muted_cyan" }, { q: 2, bag: "posh_brown" }] };
challengeArray.push(light_bronze);
var dull_red = { contains: [{ q: 2, bag: "vibrant_red" }, { q: 1, bag: "muted_gold" }, { q: 2, bag: "clear_coral" }] };
challengeArray.push(dull_red);
var mirrored_black = { contains: [{ q: 2, bag: "dull_olive" }] };
challengeArray.push(mirrored_black);
var shiny_cyan = { contains: [{ q: 1, bag: "mirrored_aqua" }, { q: 3, bag: "bright_tomato" }, { q: 5, bag: "striped_indigo" }] };
challengeArray.push(shiny_cyan);
var light_purple = { contains: [{ q: 3, bag: "bright_salmon" }, { q: 5, bag: "vibrant_black" }, { q: 2, bag: "clear_orange" }, { q: 4, bag: "plaid_olive" }] };
challengeArray.push(light_purple);
var dark_lavender = { contains: [{ q: 3, bag: "dark_turquoise" }, { q: 2, bag: "dotted_black" }] };
challengeArray.push(dark_lavender);
var vibrant_bronze = { contains: [{ q: 3, bag: "wavy_olive" }] };
challengeArray.push(vibrant_bronze);
var vibrant_salmon = { contains: [{ q: 3, bag: "dull_olive" }, { q: 4, bag: "bright_silver" }, { q: 3, bag: "muted_green" }] };
challengeArray.push(vibrant_salmon);
var pale_lime = { contains: [{ q: 1, bag: "wavy_yellow" }, { q: 4, bag: "dark_tomato" }, { q: 5, bag: "faded_aqua" }, { q: 4, bag: "muted_beige" }] };
challengeArray.push(pale_lime);
var plaid_gray = { contains: [{ q: 2, bag: "wavy_yellow" }, { q: 5, bag: "drab_turquoise" }, { q: 3, bag: "dim_gray" }] };
challengeArray.push(plaid_gray);
var mirrored_green = { contains: [{ q: 5, bag: "dull_cyan" }] };
challengeArray.push(mirrored_green);
var dim_tan = { contains: [{ q: 5, bag: "dotted_teal" }, { q: 2, bag: "clear_yellow" }, { q: 1, bag: "posh_maroon" }] };
challengeArray.push(dim_tan);
var pale_indigo = { contains: [{ q: 5, bag: "striped_indigo" }, { q: 5, bag: "clear_indigo" }, { q: 1, bag: "drab_tan" }] };
challengeArray.push(pale_indigo);
var mirrored_violet = { contains: [{ q: 2, bag: "muted_salmon" }, { q: 3, bag: "dull_violet" }] };
challengeArray.push(mirrored_violet);
var pale_salmon = { contains: [{ q: 1, bag: "mirrored_cyan" }, { q: 4, bag: "pale_gray" }, { q: 3, bag: "mirrored_fuchsia" }, { q: 1, bag: "striped_beige" }] };
challengeArray.push(pale_salmon);
var plaid_olive = { contains: [{ q: 3, bag: "dark_brown" }] };
challengeArray.push(plaid_olive);
var clear_white = { contains: [{ q: 4, bag: "plaid_violet" }, { q: 4, bag: "dull_lavender" }] };
challengeArray.push(clear_white);
var posh_yellow = { contains: [{ q: 5, bag: "light_gray" }, { q: 3, bag: "clear_green" }, { q: 3, bag: "mirrored_cyan" }, { q: 2, bag: "plaid_yellow" }] };
challengeArray.push(posh_yellow);
var bright_purple = { contains: [{ q: 1, bag: "mirrored_cyan" }, { q: 4, bag: "dim_magenta" }, { q: 2, bag: "dotted_olive" }, { q: 1, bag: "posh_tan" }] };
challengeArray.push(bright_purple);
var dark_gray = { contains: [{ q: 3, bag: "dim_turquoise" }, { q: 3, bag: "mirrored_tomato" }] };
challengeArray.push(dark_gray);
var shiny_chartreuse = { contains: [{ q: 1, bag: "dark_brown" }, { q: 2, bag: "mirrored_magenta" }, { q: 1, bag: "bright_silver" }, { q: 5, bag: "shiny_gray" }] };
challengeArray.push(shiny_chartreuse);
var dull_silver = { contains: [{ q: 3, bag: "dull_chartreuse" }, { q: 2, bag: "dull_violet" }, { q: 4, bag: "muted_aqua" }] };
challengeArray.push(dull_silver);
var clear_lime = { contains: [{ q: 4, bag: "dull_silver" }] };
challengeArray.push(clear_lime);
var faded_lavender = { contains: [{ q: 1, bag: "pale_tan" }, { q: 2, bag: "clear_turquoise" }, { q: 3, bag: "muted_green" }, { q: 1, bag: "muted_lime" }] };
challengeArray.push(faded_lavender);
var light_white = { contains: [{ q: 1, bag: "mirrored_gold" }, { q: 1, bag: "dotted_gold" }, { q: 3, bag: "pale_beige" }] };
challengeArray.push(light_white);
var posh_olive = { contains: [{ q: 3, bag: "mirrored_aqua" }, { q: 2, bag: "shiny_cyan" }] };
challengeArray.push(posh_olive);
var striped_olive = { contains: [{ q: 1, bag: "vibrant_tomato" }, { q: 3, bag: "dotted_salmon" }, { q: 3, bag: "plaid_purple" }, { q: 2, bag: "dim_brown" }] };
challengeArray.push(striped_olive);
var vibrant_gold = { contains: [{ q: 4, bag: "light_plum" }] };
challengeArray.push(vibrant_gold);
var faded_gold = { contains: [{ q: 5, bag: "shiny_green" }, { q: 4, bag: "drab_orange" }, { q: 5, bag: "faded_beige" }, { q: 5, bag: "dark_blue" }] };
challengeArray.push(faded_gold);
var faded_silver = { contains: [{ q: 4, bag: "drab_blue" }] };
challengeArray.push(faded_silver);
var drab_gray = { contains: [{ q: 1, bag: "pale_gray" }] };
challengeArray.push(drab_gray);
var posh_indigo = { contains: [{ q: 1, bag: "vibrant_teal" }, { q: 1, bag: "vibrant_aqua" }] };
challengeArray.push(posh_indigo);
var mirrored_crimson = { contains: [{ q: 5, bag: "mirrored_turquoise" }, { q: 4, bag: "mirrored_aqua" }, { q: 3, bag: "wavy_olive" }, { q: 1, bag: "dark_teal" }] };
challengeArray.push(mirrored_crimson);
var dark_olive = { contains: [{ q: 4, bag: "dim_violet" }, { q: 2, bag: "dotted_silver" }, { q: 2, bag: "dull_crimson" }, { q: 1, bag: "striped_fuchsia" }] };
challengeArray.push(dark_olive);
var bright_tan = { contains: [{ q: 5, bag: "shiny_violet" }, { q: 5, bag: "light_gray" }] };
challengeArray.push(bright_tan);
var pale_olive = { contains: [{ q: 3, bag: "faded_black" }, { q: 1, bag: "dim_aqua" }] };
challengeArray.push(pale_olive);
var drab_tan = { contains: [{ q: 2, bag: "faded_plum" }, { q: 2, bag: "posh_fuchsia" }, { q: 2, bag: "wavy_blue" }, { q: 5, bag: "dotted_lavender" }] };
challengeArray.push(drab_tan);
var striped_purple = { contains: [{ q: 4, bag: "posh_gray" }, { q: 1, bag: "shiny_plum" }, { q: 1, bag: "mirrored_crimson" }, { q: 2, bag: "plaid_orange" }] };
challengeArray.push(striped_purple);
var dotted_magenta = { contains: [{ q: 4, bag: "dull_cyan" }, { q: 1, bag: "bright_cyan" }] };
challengeArray.push(dotted_magenta);
var faded_white = { contains: [{ q: 2, bag: "dark_tomato" }, { q: 2, bag: "muted_silver" }] };
challengeArray.push(faded_white);
var pale_cyan = { contains: [{ q: 3, bag: "light_tan" }, { q: 3, bag: "dotted_brown" }, { q: 3, bag: "vibrant_aqua" }, { q: 3, bag: "drab_gray" }] };
challengeArray.push(pale_cyan);
var vibrant_tan = { contains: [{ q: 5, bag: "striped_gold" }, { q: 5, bag: "dull_gray" }, { q: 2, bag: "bright_turquoise" }, { q: 3, bag: "muted_blue" }] };
challengeArray.push(vibrant_tan);
var dark_crimson = { contains: [{ q: 4, bag: "vibrant_magenta" }, { q: 2, bag: "striped_aqua" }, { q: 1, bag: "muted_tan" }, { q: 3, bag: "vibrant_green" }] };
challengeArray.push(dark_crimson);
var dotted_red = { contains: [{ q: 1, bag: "dull_green" }, { q: 3, bag: "pale_green" }, { q: 5, bag: "pale_tomato" }, { q: 2, bag: "light_coral" }] };
challengeArray.push(dotted_red);
var dim_gold = { contains: [{ q: 3, bag: "dark_black" }, { q: 5, bag: "dotted_lavender" }, { q: 2, bag: "faded_gray" }, { q: 5, bag: "dim_beige" }] };
challengeArray.push(dim_gold);
var faded_chartreuse = { contains: [{ q: 1, bag: "clear_aqua" }, { q: 2, bag: "mirrored_black" }, { q: 1, bag: "striped_coral" }] };
challengeArray.push(faded_chartreuse);
var dark_gold = { contains: [{ q: 1, bag: "drab_coral" }, { q: 3, bag: "dark_teal" }] };
challengeArray.push(dark_gold);
var light_fuchsia = { contains: [{ q: 4, bag: "faded_salmon" }, { q: 4, bag: "shiny_gray" }] };
challengeArray.push(light_fuchsia);
var posh_blue = { contains: [{ q: 2, bag: "mirrored_tomato" }, { q: 1, bag: "drab_blue" }, { q: 4, bag: "drab_tomato" }, { q: 5, bag: "dotted_lavender" }] };
challengeArray.push(posh_blue);
var plaid_green = { contains: [{ q: 5, bag: "light_cyan" }, { q: 3, bag: "dim_turquoise" }, { q: 1, bag: "drab_teal" }] };
challengeArray.push(plaid_green);
var faded_tomato = { contains: [{ q: 4, bag: "muted_blue" }, { q: 1, bag: "striped_lime" }] };
challengeArray.push(faded_tomato);
var clear_olive = { contains: [{ q: 2, bag: "dull_silver" }, { q: 2, bag: "vibrant_yellow" }, { q: 1, bag: "pale_purple" }, { q: 2, bag: "wavy_lavender" }] };
challengeArray.push(clear_olive);
var shiny_gold = { contains: [{ q: 2, bag: "muted_aqua" }, { q: 3, bag: "bright_salmon" }, { q: 4, bag: "striped_violet" }, { q: 2, bag: "posh_brown" }] };
challengeArray.push(shiny_gold);
var clear_beige = { contains: [{ q: 5, bag: "faded_plum" }, { q: 3, bag: "dull_lavender" }] };
challengeArray.push(clear_beige);
var pale_fuchsia = { contains: [{ q: 2, bag: "wavy_lavender" }, { q: 2, bag: "striped_indigo" }, { q: 2, bag: "posh_gold" }] };
challengeArray.push(pale_fuchsia);
var wavy_silver = { contains: [{ q: 4, bag: "wavy_plum" }, { q: 1, bag: "shiny_salmon" }] };
challengeArray.push(wavy_silver);
var dotted_yellow = { contains: [{ q: 3, bag: "striped_plum" }, { q: 5, bag: "wavy_coral" }] };
challengeArray.push(dotted_yellow);
var dotted_crimson = { contains: [{ q: 1, bag: "dotted_silver" }] };
challengeArray.push(dotted_crimson);
var muted_olive = { contains: [{ q: 5, bag: "mirrored_tomato" }] };
challengeArray.push(muted_olive);
var vibrant_blue = { contains: [{ q: 1, bag: "clear_blue" }, { q: 2, bag: "mirrored_lime" }, { q: 2, bag: "dull_aqua" }] };
challengeArray.push(vibrant_blue);
var shiny_white = { contains: [{ q: 3, bag: "pale_purple" }] };
challengeArray.push(shiny_white);
var clear_chartreuse = { contains: [{ q: 4, bag: "dotted_lavender" }, { q: 3, bag: "mirrored_cyan" }] };
challengeArray.push(clear_chartreuse);
var faded_green = { contains: [{ q: 4, bag: "plaid_lime" }, { q: 4, bag: "vibrant_olive" }, { q: 3, bag: "dark_green" }, { q: 4, bag: "shiny_lime" }] };
challengeArray.push(faded_green);
var plaid_violet = { contains: [{ q: 1, bag: "striped_silver" }, { q: 2, bag: "bright_chartreuse" }] };
challengeArray.push(plaid_violet);
var clear_green = { contains: [] };
challengeArray.push(clear_green);
var vibrant_plum = { contains: [{ q: 5, bag: "clear_green" }, { q: 2, bag: "shiny_teal" }] };
challengeArray.push(vibrant_plum);
var bright_olive = { contains: [{ q: 5, bag: "light_plum" }, { q: 4, bag: "drab_beige" }] };
challengeArray.push(bright_olive);
var striped_beige = { contains: [{ q: 5, bag: "wavy_silver" }, { q: 1, bag: "shiny_teal" }, { q: 3, bag: "light_gray" }] };
challengeArray.push(striped_beige);
var faded_plum = { contains: [{ q: 3, bag: "clear_green" }, { q: 5, bag: "mirrored_chartreuse" }, { q: 1, bag: "dim_bronze" }, { q: 1, bag: "faded_coral" }] };
challengeArray.push(faded_plum);
var mirrored_tan = { contains: [{ q: 3, bag: "bright_indigo" }, { q: 1, bag: "light_yellow" }, { q: 2, bag: "muted_aqua" }, { q: 2, bag: "muted_beige" }] };
challengeArray.push(mirrored_tan);
var bright_black = { contains: [{ q: 5, bag: "pale_blue" }, { q: 4, bag: "bright_coral" }, { q: 2, bag: "wavy_plum" }, { q: 2, bag: "posh_lime" }] };
challengeArray.push(bright_black);
var striped_aqua = { contains: [{ q: 5, bag: "muted_lavender" }, { q: 1, bag: "pale_blue" }, { q: 5, bag: "vibrant_gray" }] };
challengeArray.push(striped_aqua);
var dull_chartreuse = { contains: [{ q: 1, bag: "vibrant_black" }, { q: 4, bag: "faded_salmon" }] };
challengeArray.push(dull_chartreuse);
var wavy_gray = { contains: [{ q: 3, bag: "dull_gray" }, { q: 3, bag: "light_blue" }, { q: 4, bag: "pale_teal" }] };
challengeArray.push(wavy_gray);
var dim_tomato = { contains: [{ q: 3, bag: "mirrored_chartreuse" }] };
challengeArray.push(dim_tomato);
var bright_orange = { contains: [{ q: 2, bag: "dull_indigo" }, { q: 5, bag: "plaid_violet" }, { q: 2, bag: "light_crimson" }, { q: 2, bag: "wavy_salmon" }] };
challengeArray.push(bright_orange);
var wavy_crimson = { contains: [{ q: 3, bag: "dotted_maroon" }, { q: 1, bag: "vibrant_lime" }, { q: 2, bag: "pale_indigo" }, { q: 1, bag: "striped_aqua" }] };
challengeArray.push(wavy_crimson);
var dim_lime = { contains: [{ q: 5, bag: "mirrored_magenta" }, { q: 2, bag: "plaid_beige" }] };
challengeArray.push(dim_lime);
var posh_magenta = { contains: [{ q: 5, bag: "dull_violet" }, { q: 3, bag: "wavy_gray" }] };
challengeArray.push(posh_magenta);
var vibrant_lavender = { contains: [{ q: 4, bag: "muted_violet" }, { q: 3, bag: "clear_crimson" }] };
challengeArray.push(vibrant_lavender);
var mirrored_gray = { contains: [{ q: 5, bag: "light_crimson" }, { q: 5, bag: "dull_cyan" }] };
challengeArray.push(mirrored_gray);
var dark_indigo = { contains: [{ q: 3, bag: "dark_turquoise" }, { q: 5, bag: "mirrored_turquoise" }] };
challengeArray.push(dark_indigo);
var muted_silver = { contains: [{ q: 2, bag: "dim_coral" }, { q: 1, bag: "dotted_olive" }] };
challengeArray.push(muted_silver);
var shiny_black = { contains: [{ q: 1, bag: "muted_salmon" }, { q: 2, bag: "faded_silver" }] };
challengeArray.push(shiny_black);
var faded_indigo = { contains: [{ q: 4, bag: "vibrant_gray" }, { q: 1, bag: "wavy_salmon" }, { q: 3, bag: "bright_indigo" }] };
challengeArray.push(faded_indigo);
var dim_aqua = { contains: [{ q: 1, bag: "drab_aqua" }, { q: 4, bag: "dotted_beige" }, { q: 4, bag: "faded_coral" }] };
challengeArray.push(dim_aqua);
var bright_plum = { contains: [{ q: 4, bag: "drab_olive" }, { q: 5, bag: "dim_crimson" }, { q: 1, bag: "vibrant_green" }] };
challengeArray.push(bright_plum);
var light_indigo = { contains: [{ q: 5, bag: "mirrored_chartreuse" }] };
challengeArray.push(light_indigo);
var posh_purple = { contains: [{ q: 4, bag: "plaid_magenta" }, { q: 3, bag: "pale_purple" }] };
challengeArray.push(posh_purple);
var wavy_bronze = { contains: [{ q: 4, bag: "muted_aqua" }] };
challengeArray.push(wavy_bronze);
var pale_gray = { contains: [{ q: 5, bag: "clear_orange" }, { q: 1, bag: "bright_lavender" }, { q: 4, bag: "muted_salmon" }] };
challengeArray.push(pale_gray);
var clear_bronze = { contains: [{ q: 4, bag: "light_black" }, { q: 2, bag: "drab_aqua" }] };
challengeArray.push(clear_bronze);
var wavy_green = { contains: [{ q: 1, bag: "muted_lavender" }, { q: 1, bag: "light_yellow" }, { q: 1, bag: "wavy_olive" }] };
challengeArray.push(wavy_green);
var bright_brown = { contains: [{ q: 1, bag: "dotted_black" }, { q: 1, bag: "plaid_magenta" }, { q: 4, bag: "posh_olive" }] };
challengeArray.push(bright_brown);
var vibrant_green = { contains: [{ q: 5, bag: "bright_cyan" }, { q: 3, bag: "mirrored_lime" }, { q: 5, bag: "mirrored_tan" }] };
challengeArray.push(vibrant_green);
var dull_orange = { contains: [{ q: 2, bag: "posh_chartreuse" }] };
challengeArray.push(dull_orange);
var dotted_lavender = { contains: [{ q: 5, bag: "vibrant_gray" }, { q: 4, bag: "plaid_silver" }] };
challengeArray.push(dotted_lavender);
var dim_maroon = { contains: [{ q: 2, bag: "pale_chartreuse" }, { q: 4, bag: "striped_beige" }, { q: 2, bag: "shiny_gold" }] };
challengeArray.push(dim_maroon);
var shiny_turquoise = { contains: [{ q: 2, bag: "light_orange" }] };
challengeArray.push(shiny_turquoise);
var striped_brown = { contains: [{ q: 5, bag: "muted_brown" }, { q: 4, bag: "dotted_bronze" }, { q: 5, bag: "striped_plum" }, { q: 5, bag: "striped_green" }] };
challengeArray.push(striped_brown);
var plaid_magenta = { contains: [{ q: 5, bag: "faded_salmon" }, { q: 5, bag: "dark_black" }, { q: 5, bag: "muted_indigo" }, { q: 4, bag: "pale_blue" }] };
challengeArray.push(plaid_magenta);
var faded_cyan = { contains: [{ q: 5, bag: "muted_lavender" }, { q: 1, bag: "bright_fuchsia" }, { q: 1, bag: "mirrored_tomato" }] };
challengeArray.push(faded_cyan);
var muted_yellow = { contains: [{ q: 1, bag: "drab_salmon" }, { q: 5, bag: "mirrored_cyan" }, { q: 5, bag: "drab_coral" }] };
challengeArray.push(muted_yellow);
var bright_teal = { contains: [{ q: 4, bag: "dotted_lime" }, { q: 2, bag: "plaid_magenta" }, { q: 3, bag: "mirrored_tomato" }, { q: 5, bag: "striped_cyan" }] };
challengeArray.push(bright_teal);
var wavy_indigo = { contains: [{ q: 3, bag: "dotted_silver" }, { q: 4, bag: "clear_brown" }, { q: 3, bag: "posh_gray" }, { q: 1, bag: "dull_red" }] };
challengeArray.push(wavy_indigo);
var striped_tomato = { contains: [{ q: 1, bag: "dotted_olive" }] };
challengeArray.push(striped_tomato);
var dim_olive = { contains: [{ q: 1, bag: "dotted_indigo" }, { q: 2, bag: "dotted_lime" }, { q: 2, bag: "muted_silver" }] };
challengeArray.push(dim_olive);
var plaid_black = { contains: [{ q: 3, bag: "dim_green" }, { q: 1, bag: "posh_bronze" }, { q: 2, bag: "wavy_orange" }, { q: 1, bag: "muted_gold" }] };
challengeArray.push(plaid_black);
var dark_red = { contains: [{ q: 1, bag: "dotted_beige" }, { q: 5, bag: "dotted_olive" }, { q: 1, bag: "drab_turquoise" }, { q: 1, bag: "light_tan" }] };
challengeArray.push(dark_red);
var light_red = { contains: [{ q: 1, bag: "muted_lavender" }, { q: 1, bag: "muted_teal" }, { q: 5, bag: "bright_white" }, { q: 4, bag: "dotted_fuchsia" }] };
challengeArray.push(light_red);
var posh_coral = { contains: [{ q: 5, bag: "posh_silver" }, { q: 1, bag: "vibrant_olive" }] };
challengeArray.push(posh_coral);
var wavy_lavender = { contains: [{ q: 3, bag: "bright_indigo" }, { q: 4, bag: "dim_bronze" }] };
challengeArray.push(wavy_lavender);
var striped_lavender = { contains: [{ q: 1, bag: "striped_tomato" }] };
challengeArray.push(striped_lavender);
var wavy_cyan = { contains: [{ q: 2, bag: "shiny_salmon" }, { q: 4, bag: "drab_aqua" }, { q: 4, bag: "faded_coral" }, { q: 1, bag: "dotted_olive" }] };
challengeArray.push(wavy_cyan);
var light_brown = { contains: [{ q: 2, bag: "faded_gray" }, { q: 5, bag: "dark_brown" }] };
challengeArray.push(light_brown);
var dark_black = { contains: [{ q: 2, bag: "posh_brown" }] };
challengeArray.push(dark_black);
var dark_tan = { contains: [{ q: 1, bag: "striped_cyan" }, { q: 3, bag: "plaid_salmon" }] };
challengeArray.push(dark_tan);
var muted_maroon = { contains: [{ q: 4, bag: "bright_bronze" }, { q: 3, bag: "dotted_lavender" }, { q: 4, bag: "pale_fuchsia" }, { q: 1, bag: "vibrant_red" }] };
challengeArray.push(muted_maroon);
var faded_fuchsia = { contains: [{ q: 5, bag: "light_purple" }, { q: 3, bag: "dim_gray" }] };
challengeArray.push(faded_fuchsia);
var shiny_bronze = { contains: [{ q: 3, bag: "mirrored_magenta" }, { q: 3, bag: "light_aqua" }, { q: 3, bag: "drab_plum" }, { q: 1, bag: "vibrant_salmon" }] };
challengeArray.push(shiny_bronze);
var light_gray = { contains: [{ q: 1, bag: "striped_fuchsia" }, { q: 1, bag: "shiny_gold" }, { q: 3, bag: "clear_gold" }, { q: 3, bag: "bright_fuchsia" }] };
challengeArray.push(light_gray);
var dim_turquoise = { contains: [{ q: 5, bag: "dull_aqua" }] };
challengeArray.push(dim_turquoise);
var faded_coral = { contains: [] };
challengeArray.push(faded_coral);
var dark_maroon = { contains: [{ q: 1, bag: "dark_turquoise" }, { q: 4, bag: "light_fuchsia" }, { q: 5, bag: "shiny_plum" }] };
challengeArray.push(dark_maroon);
var striped_black = { contains: [{ q: 2, bag: "faded_tomato" }, { q: 1, bag: "vibrant_turquoise" }, { q: 4, bag: "muted_bronze" }] };
challengeArray.push(striped_black);
var plaid_gold = { contains: [{ q: 4, bag: "wavy_aqua" }, { q: 4, bag: "vibrant_white" }] };
challengeArray.push(plaid_gold);
var dim_gray = { contains: [{ q: 5, bag: "wavy_silver" }] };
challengeArray.push(dim_gray);
var wavy_brown = { contains: [{ q: 3, bag: "bright_bronze" }, { q: 2, bag: "dotted_gray" }] };
challengeArray.push(wavy_brown);
var bright_fuchsia = { contains: [{ q: 2, bag: "mirrored_aqua" }, { q: 4, bag: "shiny_green" }, { q: 5, bag: "vibrant_black" }, { q: 1, bag: "bright_tomato" }] };
challengeArray.push(bright_fuchsia);
var dark_chartreuse = { contains: [{ q: 5, bag: "shiny_white" }, { q: 4, bag: "dotted_salmon" }, { q: 5, bag: "shiny_purple" }, { q: 5, bag: "faded_red" }] };
challengeArray.push(dark_chartreuse);
var dark_plum = { contains: [{ q: 2, bag: "clear_gold" }, { q: 2, bag: "pale_gray" }] };
challengeArray.push(dark_plum);
var dull_maroon = { contains: [{ q: 2, bag: "mirrored_chartreuse" }, { q: 1, bag: "clear_orange" }, { q: 4, bag: "mirrored_black" }, { q: 5, bag: "clear_violet" }] };
challengeArray.push(dull_maroon);
var plaid_maroon = { contains: [{ q: 3, bag: "bright_purple" }, { q: 3, bag: "bright_red" }, { q: 3, bag: "faded_purple" }] };
challengeArray.push(plaid_maroon);
var dull_coral = { contains: [{ q: 5, bag: "drab_gray" }, { q: 2, bag: "dotted_chartreuse" }] };
challengeArray.push(dull_coral);
var shiny_coral = { contains: [{ q: 3, bag: "vibrant_black" }, { q: 4, bag: "bright_chartreuse" }, { q: 3, bag: "faded_indigo" }] };
challengeArray.push(shiny_coral);
var clear_crimson = { contains: [{ q: 1, bag: "drab_tomato" }, { q: 4, bag: "mirrored_white" }, { q: 2, bag: "dim_violet" }] };
challengeArray.push(clear_crimson);
var drab_aqua = { contains: [{ q: 2, bag: "dull_chartreuse" }, { q: 1, bag: "pale_crimson" }, { q: 4, bag: "posh_lime" }] };
challengeArray.push(drab_aqua);
var vibrant_aqua = { contains: [{ q: 1, bag: "wavy_cyan" }] };
challengeArray.push(vibrant_aqua);
var striped_fuchsia = { contains: [{ q: 5, bag: "bright_tomato" }, { q: 2, bag: "wavy_plum" }, { q: 2, bag: "faded_plum" }, { q: 4, bag: "clear_green" }] };
challengeArray.push(striped_fuchsia);
var shiny_plum = { contains: [{ q: 2, bag: "posh_red" }, { q: 3, bag: "faded_plum" }, { q: 2, bag: "striped_beige" }, { q: 1, bag: "mirrored_turquoise" }] };
challengeArray.push(shiny_plum);
var muted_purple = { contains: [{ q: 5, bag: "bright_white" }, { q: 4, bag: "dotted_chartreuse" }, { q: 1, bag: "drab_black" }] };
challengeArray.push(muted_purple);
var posh_bronze = { contains: [{ q: 3, bag: "muted_cyan" }, { q: 4, bag: "faded_coral" }, { q: 3, bag: "wavy_plum" }] };
challengeArray.push(posh_bronze);
var light_turquoise = { contains: [{ q: 4, bag: "mirrored_silver" }, { q: 2, bag: "bright_gray" }, { q: 5, bag: "mirrored_maroon" }] };
challengeArray.push(light_turquoise);
var vibrant_fuchsia = { contains: [{ q: 5, bag: "faded_tomato" }, { q: 1, bag: "posh_fuchsia" }, { q: 3, bag: "posh_maroon" }, { q: 1, bag: "plaid_salmon" }] };
challengeArray.push(vibrant_fuchsia);
var muted_orange = { contains: [{ q: 1, bag: "striped_gray" }, { q: 2, bag: "dull_bronze" }, { q: 1, bag: "dull_silver" }] };
challengeArray.push(muted_orange);
var dotted_cyan = { contains: [{ q: 4, bag: "clear_olive" }] };
challengeArray.push(dotted_cyan);
var dull_gray = { contains: [{ q: 5, bag: "mirrored_maroon" }, { q: 4, bag: "dim_coral" }, { q: 2, bag: "muted_olive" }] };
challengeArray.push(dull_gray);
var clear_red = { contains: [{ q: 3, bag: "dark_fuchsia" }, { q: 4, bag: "mirrored_fuchsia" }] };
challengeArray.push(clear_red);
var clear_indigo = { contains: [{ q: 4, bag: "muted_salmon" }] };
challengeArray.push(clear_indigo);
var striped_green = { contains: [{ q: 4, bag: "dull_maroon" }] };
challengeArray.push(striped_green);
var vibrant_chartreuse = { contains: [{ q: 1, bag: "muted_aqua" }, { q: 5, bag: "clear_lime" }] };
challengeArray.push(vibrant_chartreuse);
var mirrored_beige = { contains: [{ q: 3, bag: "dark_teal" }] };
challengeArray.push(mirrored_beige);
var vibrant_lime = { contains: [{ q: 4, bag: "plaid_fuchsia" }] };
challengeArray.push(vibrant_lime);
var dotted_brown = { contains: [{ q: 3, bag: "bright_gray" }, { q: 5, bag: "wavy_yellow" }, { q: 1, bag: "muted_maroon" }] };
challengeArray.push(dotted_brown);
var striped_lime = { contains: [{ q: 3, bag: "muted_lavender" }] };
challengeArray.push(striped_lime);
var vibrant_magenta = { contains: [{ q: 4, bag: "faded_coral" }, { q: 1, bag: "dim_bronze" }] };
challengeArray.push(vibrant_magenta);
var drab_olive = { contains: [{ q: 3, bag: "shiny_indigo" }, { q: 1, bag: "dim_lime" }] };
challengeArray.push(drab_olive);
var dotted_orange = { contains: [{ q: 5, bag: "muted_white" }, { q: 3, bag: "striped_gray" }] };
challengeArray.push(dotted_orange);
var bright_lavender = { contains: [{ q: 4, bag: "faded_purple" }, { q: 1, bag: "bright_chartreuse" }] };
challengeArray.push(bright_lavender);
var pale_maroon = { contains: [{ q: 5, bag: "vibrant_gray" }, { q: 4, bag: "shiny_red" }, { q: 3, bag: "drab_aqua" }, { q: 4, bag: "wavy_tan" }] };
challengeArray.push(pale_maroon);
var dotted_aqua = { contains: [{ q: 1, bag: "mirrored_lime" }] };
challengeArray.push(dotted_aqua);
var wavy_orange = { contains: [{ q: 3, bag: "dull_green" }, { q: 4, bag: "light_lavender" }] };
challengeArray.push(wavy_orange);
var faded_maroon = { contains: [{ q: 3, bag: "vibrant_gray" }, { q: 2, bag: "muted_lavender" }] };
challengeArray.push(faded_maroon);
var dim_silver = { contains: [{ q: 2, bag: "dotted_chartreuse" }, { q: 4, bag: "clear_violet" }, { q: 2, bag: "clear_red" }] };
challengeArray.push(dim_silver);
var dull_turquoise = { contains: [{ q: 5, bag: "faded_olive" }, { q: 3, bag: "drab_magenta" }] };
challengeArray.push(dull_turquoise);
var shiny_red = { contains: [{ q: 4, bag: "clear_tan" }, { q: 2, bag: "dull_red" }, { q: 5, bag: "dark_tomato" }] };
challengeArray.push(shiny_red);
var posh_orange = { contains: [{ q: 4, bag: "muted_lavender" }, { q: 5, bag: "dim_violet" }, { q: 5, bag: "striped_aqua" }] };
challengeArray.push(posh_orange);
var plaid_white = { contains: [{ q: 5, bag: "mirrored_cyan" }, { q: 2, bag: "light_brown" }, { q: 3, bag: "muted_tan" }] };
challengeArray.push(plaid_white);
var shiny_magenta = { contains: [{ q: 3, bag: "faded_coral" }, { q: 5, bag: "posh_gray" }] };
challengeArray.push(shiny_magenta);
var bright_bronze = { contains: [{ q: 4, bag: "wavy_blue" }, { q: 2, bag: "clear_violet" }] };
challengeArray.push(bright_bronze);
var mirrored_orange = { contains: [{ q: 2, bag: "dim_green" }, { q: 2, bag: "striped_red" }, { q: 4, bag: "drab_plum" }, { q: 1, bag: "pale_teal" }] };
challengeArray.push(mirrored_orange);